package bybit

import (
	"github.com/banbox/banexg"
	"github.com/banbox/banexg/errs"
)

func New(Options map[string]interface{}) (*Bybit, *errs.Error) {
	hostName := "bybit.com"
	exg := &Bybit{
		Exchange: &banexg.Exchange{
			ExgInfo: &banexg.ExgInfo{
				ID:        "bybit",
				Name:      "Bybit",
				Countries: []string{"VG"},
			},
			RateLimit: 20,
			Options:   Options,
			Hosts: &banexg.ExgHosts{
				Test: map[string]string{
					HostPublic:  "https://api-testnet." + hostName,
					HostPrivate: "https://api-testnet." + hostName,
				},
				Prod: map[string]string{
					HostPublic:  "https://api." + hostName,
					HostPrivate: "https://api." + hostName,
				},
				Www: "https://www.bybit.com",
				Doc: []string{
					"https://bybit-exchange.github.io/docs/",
				},
				Fees: "https://www.bybit.com/en/help-center/article/Trading-Fee-Structure",
			},
			Fees: &banexg.ExgFee{
				Main: &banexg.TradeFee{
					FeeSide:    "get",
					TierBased:  false,
					Percentage: true,
					Taker:      0.001,
					Maker:      0.001,
				},
				Linear: &banexg.TradeFee{
					FeeSide:    "quote",
					TierBased:  false,
					Percentage: true,
					Taker:      0.00055,
					Maker:      0.0002,
				},
				Inverse: &banexg.TradeFee{
					FeeSide:    "base",
					TierBased:  false,
					Percentage: true,
					Taker:      0.00055,
					Maker:      0.0002,
				},
				Option: &banexg.TradeFee{
					FeeSide:    "quote",
					TierBased:  false,
					Percentage: true,
					Taker:      0.0002,
					Maker:      0.0002,
				},
			},
			Apis: map[string]*banexg.Entry{
				"publicGetSpotV3PublicSymbols":                                 {Path: "spot/v3/public/symbols", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicQuoteDepth":                              {Path: "spot/v3/public/quote/depth", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicQuoteDepthMerged":                        {Path: "spot/v3/public/quote/depth/merged", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicQuoteTrades":                             {Path: "spot/v3/public/quote/trades", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicQuoteKline":                              {Path: "spot/v3/public/quote/kline", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicQuoteTicker24hr":                         {Path: "spot/v3/public/quote/ticker/24hr", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicQuoteTickerPrice":                        {Path: "spot/v3/public/quote/ticker/price", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicQuoteTickerBookTicker":                   {Path: "spot/v3/public/quote/ticker/bookTicker", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicServerTime":                              {Path: "spot/v3/public/server-time", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicInfos":                                   {Path: "spot/v3/public/infos", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicMarginProductInfos":                      {Path: "spot/v3/public/margin-product-infos", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetSpotV3PublicMarginEnsureTokens":                      {Path: "spot/v3/public/margin-ensure-tokens", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetV3PublicTime":                                        {Path: "v3/public/time", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetContractV3PublicCopytradingSymbolList":               {Path: "contract/v3/public/copytrading/symbol/list", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicOrderBookL2":                      {Path: "derivatives/v3/public/order-book/L2", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicKline":                            {Path: "derivatives/v3/public/kline", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicTickers":                          {Path: "derivatives/v3/public/tickers", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicInstrumentsInfo":                  {Path: "derivatives/v3/public/instruments-info", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicMarkPriceKline":                   {Path: "derivatives/v3/public/mark-price-kline", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicIndexPriceKline":                  {Path: "derivatives/v3/public/index-price-kline", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicFundingHistoryFundingRate":        {Path: "derivatives/v3/public/funding/history-funding-rate", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicRiskLimitList":                    {Path: "derivatives/v3/public/risk-limit/list", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicDeliveryPrice":                    {Path: "derivatives/v3/public/delivery-price", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicRecentTrade":                      {Path: "derivatives/v3/public/recent-trade", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicOpenInterest":                     {Path: "derivatives/v3/public/open-interest", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetDerivativesV3PublicInsurance":                        {Path: "derivatives/v3/public/insurance", Host: HostPublic, Method: "GET", Cost: 1},
				"publicGetV5AnnouncementsIndex":                                {Path: "v5/announcements/index", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketTime":                                        {Path: "v5/market/time", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketKline":                                       {Path: "v5/market/kline", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketMarkPriceKline":                              {Path: "v5/market/mark-price-kline", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketIndexPriceKline":                             {Path: "v5/market/index-price-kline", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketPremiumIndexPriceKline":                      {Path: "v5/market/premium-index-price-kline", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketInstrumentsInfo":                             {Path: "v5/market/instruments-info", Host: HostPublic, Method: "GET", CacheSecs: 3600, Cost: 5},
				"publicGetV5MarketOrderbook":                                   {Path: "v5/market/orderbook", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketTickers":                                     {Path: "v5/market/tickers", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketFundingHistory":                              {Path: "v5/market/funding/history", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketRecentTrade":                                 {Path: "v5/market/recent-trade", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketOpenInterest":                                {Path: "v5/market/open-interest", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketHistoricalVolatility":                        {Path: "v5/market/historical-volatility", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketInsurance":                                   {Path: "v5/market/insurance", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketRiskLimit":                                   {Path: "v5/market/risk-limit", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketDeliveryPrice":                               {Path: "v5/market/delivery-price", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5MarketAccountRatio":                                {Path: "v5/market/account-ratio", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5SpotLeverTokenInfo":                                {Path: "v5/spot-lever-token/info", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5SpotLeverTokenReference":                           {Path: "v5/spot-lever-token/reference", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5SpotMarginTradeData":                               {Path: "v5/spot-margin-trade/data", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5SpotCrossMarginTradeData":                          {Path: "v5/spot-cross-margin-trade/data", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5SpotCrossMarginTradePledgeToken":                   {Path: "v5/spot-cross-margin-trade/pledge-token", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5SpotCrossMarginTradeBorrowToken":                   {Path: "v5/spot-cross-margin-trade/borrow-token", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5InsLoanProductInfos":                               {Path: "v5/ins-loan/product-infos", Host: HostPublic, Method: "GET", Cost: 5},
				"publicGetV5InsLoanEnsureTokensConvert":                        {Path: "v5/ins-loan/ensure-tokens-convert", Host: HostPublic, Method: "GET", Cost: 5},
				"privateGetV5MarketInstrumentsInfo":                            {Path: "v5/market/instruments-info", Host: HostPrivate, Method: "GET", CacheSecs: 3600, Cost: 5},
				"privateGetV2PrivateWalletFundRecords":                         {Path: "v2/private/wallet/fund/records", Host: HostPrivate, Method: "GET", Cost: 25},
				"privateGetSpotV3PrivateOrder":                                 {Path: "spot/v3/private/order", Host: HostPrivate, Method: "GET", Cost: 2.5},
				"privateGetSpotV3PrivateOpenOrders":                            {Path: "spot/v3/private/open-orders", Host: HostPrivate, Method: "GET", Cost: 2.5},
				"privateGetSpotV3PrivateHistoryOrders":                         {Path: "spot/v3/private/history-orders", Host: HostPrivate, Method: "GET", Cost: 2.5},
				"privateGetSpotV3PrivateMyTrades":                              {Path: "spot/v3/private/my-trades", Host: HostPrivate, Method: "GET", Cost: 2.5},
				"privateGetSpotV3PrivateAccount":                               {Path: "spot/v3/private/account", Host: HostPrivate, Method: "GET", Cost: 2.5},
				"privateGetSpotV3PrivateReference":                             {Path: "spot/v3/private/reference", Host: HostPrivate, Method: "GET", Cost: 2.5},
				"privateGetSpotV3PrivateRecord":                                {Path: "spot/v3/private/record", Host: HostPrivate, Method: "GET", Cost: 2.5},
				"privateGetSpotV3PrivateCrossMarginOrders":                     {Path: "spot/v3/private/cross-margin-orders", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetSpotV3PrivateCrossMarginAccount":                    {Path: "spot/v3/private/cross-margin-account", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetSpotV3PrivateCrossMarginLoanInfo":                   {Path: "spot/v3/private/cross-margin-loan-info", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetSpotV3PrivateCrossMarginRepayHistory":               {Path: "spot/v3/private/cross-margin-repay-history", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetSpotV3PrivateMarginLoanInfos":                       {Path: "spot/v3/private/margin-loan-infos", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetSpotV3PrivateMarginRepaidInfos":                     {Path: "spot/v3/private/margin-repaid-infos", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetSpotV3PrivateMarginLtv":                             {Path: "spot/v3/private/margin-ltv", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetAssetV3PrivateTransferInterTransferListQuery":       {Path: "asset/v3/private/transfer/inter-transfer/list/query", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetAssetV3PrivateTransferSubMemberListQuery":           {Path: "asset/v3/private/transfer/sub-member/list/query", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetAssetV3PrivateTransferSubMemberTransferListQuery":   {Path: "asset/v3/private/transfer/sub-member-transfer/list/query", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetAssetV3PrivateTransferUniversalTransferListQuery":   {Path: "asset/v3/private/transfer/universal-transfer/list/query", Host: HostPrivate, Method: "GET", Cost: 25},
				"privateGetAssetV3PrivateCoinInfoQuery":                        {Path: "asset/v3/private/coin-info/query", Host: HostPrivate, Method: "GET", Cost: 25},
				"privateGetAssetV3PrivateDepositAddressQuery":                  {Path: "asset/v3/private/deposit/address/query", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetContractV3PrivateCopytradingOrderList":              {Path: "contract/v3/private/copytrading/order/list", Host: HostPrivate, Method: "GET", Cost: 30},
				"privateGetContractV3PrivateCopytradingPositionList":           {Path: "contract/v3/private/copytrading/position/list", Host: HostPrivate, Method: "GET", Cost: 40},
				"privateGetContractV3PrivateCopytradingWalletBalance":          {Path: "contract/v3/private/copytrading/wallet/balance", Host: HostPrivate, Method: "GET", Cost: 25},
				"privateGetContractV3PrivatePositionLimitInfo":                 {Path: "contract/v3/private/position/limit-info", Host: HostPrivate, Method: "GET", Cost: 25},
				"privateGetContractV3PrivateOrderUnfilledOrders":               {Path: "contract/v3/private/order/unfilled-orders", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetContractV3PrivateOrderList":                         {Path: "contract/v3/private/order/list", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetContractV3PrivatePositionList":                      {Path: "contract/v3/private/position/list", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetContractV3PrivateExecutionList":                     {Path: "contract/v3/private/execution/list", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetContractV3PrivatePositionClosedPnl":                 {Path: "contract/v3/private/position/closed-pnl", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetContractV3PrivateAccountWalletBalance":              {Path: "contract/v3/private/account/wallet/balance", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetContractV3PrivateAccountFeeRate":                    {Path: "contract/v3/private/account/fee-rate", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetContractV3PrivateAccountWalletFundRecords":          {Path: "contract/v3/private/account/wallet/fund-records", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateOrderUnfilledOrders":                {Path: "unified/v3/private/order/unfilled-orders", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateOrderList":                          {Path: "unified/v3/private/order/list", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivatePositionList":                       {Path: "unified/v3/private/position/list", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateExecutionList":                      {Path: "unified/v3/private/execution/list", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateDeliveryRecord":                     {Path: "unified/v3/private/delivery-record", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateSettlementRecord":                   {Path: "unified/v3/private/settlement-record", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateAccountWalletBalance":               {Path: "unified/v3/private/account/wallet/balance", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateAccountTransactionLog":              {Path: "unified/v3/private/account/transaction-log", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateAccountBorrowHistory":               {Path: "unified/v3/private/account/borrow-history", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateAccountBorrowRate":                  {Path: "unified/v3/private/account/borrow-rate", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUnifiedV3PrivateAccountInfo":                        {Path: "unified/v3/private/account/info", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetUserV3PrivateFrozenSubMember":                       {Path: "user/v3/private/frozen-sub-member", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetUserV3PrivateQuerySubMembers":                       {Path: "user/v3/private/query-sub-members", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetUserV3PrivateQueryApi":                              {Path: "user/v3/private/query-api", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetUserV3PrivateGetMemberType":                         {Path: "user/v3/private/get-member-type", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetAssetV3PrivateTransferTransferCoinListQuery":        {Path: "asset/v3/private/transfer/transfer-coin/list/query", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetAssetV3PrivateTransferAccountCoinBalanceQuery":      {Path: "asset/v3/private/transfer/account-coin/balance/query", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetAssetV3PrivateTransferAccountCoinsBalanceQuery":     {Path: "asset/v3/private/transfer/account-coins/balance/query", Host: HostPrivate, Method: "GET", Cost: 25},
				"privateGetAssetV3PrivateTransferAssetInfoQuery":               {Path: "asset/v3/private/transfer/asset-info/query", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetAssetV3PublicDepositAllowedDepositListQuery":        {Path: "asset/v3/public/deposit/allowed-deposit-list/query", Host: HostPrivate, Method: "GET", Cost: 0.17},
				"privateGetAssetV3PrivateDepositRecordQuery":                   {Path: "asset/v3/private/deposit/record/query", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetAssetV3PrivateWithdrawRecordQuery":                  {Path: "asset/v3/private/withdraw/record/query", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetV5OrderRealtime":                                    {Path: "v5/order/realtime", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5OrderHistory":                                     {Path: "v5/order/history", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5OrderSpotBorrowCheck":                             {Path: "v5/order/spot-borrow-check", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5PositionList":                                     {Path: "v5/position/list", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5ExecutionList":                                    {Path: "v5/execution/list", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5PositionClosedPnl":                                {Path: "v5/position/closed-pnl", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5PositionMoveHistory":                              {Path: "v5/position/move-history", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5PreUpgradeOrderHistory":                           {Path: "v5/pre-upgrade/order/history", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5PreUpgradeExecutionList":                          {Path: "v5/pre-upgrade/execution/list", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5PreUpgradePositionClosedPnl":                      {Path: "v5/pre-upgrade/position/closed-pnl", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5PreUpgradeAccountTransactionLog":                  {Path: "v5/pre-upgrade/account/transaction-log", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5PreUpgradeAssetDeliveryRecord":                    {Path: "v5/pre-upgrade/asset/delivery-record", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5PreUpgradeAssetSettlementRecord":                  {Path: "v5/pre-upgrade/asset/settlement-record", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5AccountWalletBalance":                             {Path: "v5/account/wallet-balance", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5AccountBorrowHistory":                             {Path: "v5/account/borrow-history", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5AccountCollateralInfo":                            {Path: "v5/account/collateral-info", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5AssetCoinGreeks":                                  {Path: "v5/asset/coin-greeks", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5AccountFeeRate":                                   {Path: "v5/account/fee-rate", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetV5AccountInfo":                                      {Path: "v5/account/info", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5AccountTransactionLog":                            {Path: "v5/account/transaction-log", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5AccountContractTransactionLog":                    {Path: "v5/account/contract-transaction-log", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5AccountSmpGroup":                                  {Path: "v5/account/smp-group", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5AccountMmpState":                                  {Path: "v5/account/mmp-state", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5AssetExchangeQueryCoinList":                       {Path: "v5/asset/exchange/query-coin-list", Host: HostPrivate, Method: "GET", Cost: 0.5},
				"privateGetV5AssetExchangeConvertResultQuery":                  {Path: "v5/asset/exchange/convert-result-query", Host: HostPrivate, Method: "GET", Cost: 0.5},
				"privateGetV5AssetExchangeQueryConvertHistory":                 {Path: "v5/asset/exchange/query-convert-history", Host: HostPrivate, Method: "GET", Cost: 0.5},
				"privateGetV5AssetExchangeOrderRecord":                         {Path: "v5/asset/exchange/order-record", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5AssetDeliveryRecord":                              {Path: "v5/asset/delivery-record", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5AssetSettlementRecord":                            {Path: "v5/asset/settlement-record", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5AssetTransferQueryAssetInfo":                      {Path: "v5/asset/transfer/query-asset-info", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetV5AssetTransferQueryAccountCoinsBalance":            {Path: "v5/asset/transfer/query-account-coins-balance", Host: HostPrivate, Method: "GET", Cost: 25},
				"privateGetV5AssetTransferQueryAccountCoinBalance":             {Path: "v5/asset/transfer/query-account-coin-balance", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetV5AssetTransferQueryTransferCoinList":               {Path: "v5/asset/transfer/query-transfer-coin-list", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetV5AssetTransferQueryInterTransferList":              {Path: "v5/asset/transfer/query-inter-transfer-list", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetV5AssetTransferQuerySubMemberList":                  {Path: "v5/asset/transfer/query-sub-member-list", Host: HostPrivate, Method: "GET", Cost: 50},
				"privateGetV5AssetTransferQueryUniversalTransferList":          {Path: "v5/asset/transfer/query-universal-transfer-list", Host: HostPrivate, Method: "GET", Cost: 25},
				"privateGetV5AssetDepositQueryAllowedList":                     {Path: "v5/asset/deposit/query-allowed-list", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5AssetDepositQueryRecord":                          {Path: "v5/asset/deposit/query-record", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetV5AssetDepositQuerySubMemberRecord":                 {Path: "v5/asset/deposit/query-sub-member-record", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetV5AssetDepositQueryInternalRecord":                  {Path: "v5/asset/deposit/query-internal-record", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5AssetDepositQueryAddress":                         {Path: "v5/asset/deposit/query-address", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetV5AssetDepositQuerySubMemberAddress":                {Path: "v5/asset/deposit/query-sub-member-address", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetV5AssetCoinQueryInfo":                               {Path: "v5/asset/coin/query-info", Host: HostPrivate, Method: "GET", CacheSecs: 3600, Cost: 28},
				"privateGetV5AssetWithdrawQueryRecord":                         {Path: "v5/asset/withdraw/query-record", Host: HostPrivate, Method: "GET", Cost: 10},
				"privateGetV5AssetWithdrawWithdrawableAmount":                  {Path: "v5/asset/withdraw/withdrawable-amount", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5AssetWithdrawVaspList":                            {Path: "v5/asset/withdraw/vasp/list", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5UserQuerySubMembers":                              {Path: "v5/user/query-sub-members", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5UserQueryApi":                                     {Path: "v5/user/query-api", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5UserSubApikeys":                                   {Path: "v5/user/sub-apikeys", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5UserGetMemberType":                                {Path: "v5/user/get-member-type", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5UserAffCustomerInfo":                              {Path: "v5/user/aff-customer-info", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5UserDelSubmember":                                 {Path: "v5/user/del-submember", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5UserSubmembers":                                   {Path: "v5/user/submembers", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5SpotLeverTokenOrderRecord":                        {Path: "v5/spot-lever-token/order-record", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5SpotMarginTradeInterestRateHistory":               {Path: "v5/spot-margin-trade/interest-rate-history", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5SpotMarginTradeState":                             {Path: "v5/spot-margin-trade/state", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5SpotCrossMarginTradeLoanInfo":                     {Path: "v5/spot-cross-margin-trade/loan-info", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5SpotCrossMarginTradeAccount":                      {Path: "v5/spot-cross-margin-trade/account", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5SpotCrossMarginTradeOrders":                       {Path: "v5/spot-cross-margin-trade/orders", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5SpotCrossMarginTradeRepayHistory":                 {Path: "v5/spot-cross-margin-trade/repay-history", Host: HostPrivate, Method: "GET", Cost: 1},
				"privateGetV5InsLoanProductInfos":                              {Path: "v5/ins-loan/product-infos", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5InsLoanEnsureTokensConvert":                       {Path: "v5/ins-loan/ensure-tokens-convert", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5InsLoanLoanOrder":                                 {Path: "v5/ins-loan/loan-order", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5InsLoanRepaidHistory":                             {Path: "v5/ins-loan/repaid-history", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5InsLoanLtvConvert":                                {Path: "v5/ins-loan/ltv-convert", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5LendingInfo":                                      {Path: "v5/lending/info", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5LendingHistoryOrder":                              {Path: "v5/lending/history-order", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5LendingAccount":                                   {Path: "v5/lending/account", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5BrokerEarningRecord":                              {Path: "v5/broker/earning-record", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5BrokerEarningsInfo":                               {Path: "v5/broker/earnings-info", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5BrokerAccountInfo":                                {Path: "v5/broker/account-info", Host: HostPrivate, Method: "GET", Cost: 5},
				"privateGetV5BrokerAssetQuerySubMemberDepositRecord":           {Path: "v5/broker/asset/query-sub-member-deposit-record", Host: HostPrivate, Method: "GET", Cost: 10},
				"privatePostOptionUsdcOpenapiPrivateV1PlaceOrder":              {Path: "option/usdc/openapi/private/v1/place-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostOptionUsdcOpenapiPrivateV1ReplaceOrder":            {Path: "option/usdc/openapi/private/v1/replace-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostOptionUsdcOpenapiPrivateV1CancelOrder":             {Path: "option/usdc/openapi/private/v1/cancel-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostOptionUsdcOpenapiPrivateV1CancelAll":               {Path: "option/usdc/openapi/private/v1/cancel-all", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostOptionUsdcOpenapiPrivateV1QueryActiveOrders":       {Path: "option/usdc/openapi/private/v1/query-active-orders", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostOptionUsdcOpenapiPrivateV1QueryOrderHistory":       {Path: "option/usdc/openapi/private/v1/query-order-history", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostOptionUsdcOpenapiPrivateV1ExecutionList":           {Path: "option/usdc/openapi/private/v1/execution-list", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostOptionUsdcOpenapiPrivateV1QueryPosition":           {Path: "option/usdc/openapi/private/v1/query-position", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostPerpetualUsdcOpenapiPrivateV1PlaceOrder":           {Path: "perpetual/usdc/openapi/private/v1/place-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostPerpetualUsdcOpenapiPrivateV1ReplaceOrder":         {Path: "perpetual/usdc/openapi/private/v1/replace-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostPerpetualUsdcOpenapiPrivateV1CancelOrder":          {Path: "perpetual/usdc/openapi/private/v1/cancel-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostPerpetualUsdcOpenapiPrivateV1CancelAll":            {Path: "perpetual/usdc/openapi/private/v1/cancel-all", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostPerpetualUsdcOpenapiPrivateV1PositionLeverageSave": {Path: "perpetual/usdc/openapi/private/v1/position/leverage/save", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostSpotV3PrivateOrder":                                {Path: "spot/v3/private/order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostSpotV3PrivateCancelOrder":                          {Path: "spot/v3/private/cancel-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostSpotV3PrivateCancelOrders":                         {Path: "spot/v3/private/cancel-orders", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostSpotV3PrivateCancelOrdersByIds":                    {Path: "spot/v3/private/cancel-orders-by-ids", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostSpotV3PrivatePurchase":                             {Path: "spot/v3/private/purchase", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostSpotV3PrivateRedeem":                               {Path: "spot/v3/private/redeem", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostSpotV3PrivateCrossMarginLoan":                      {Path: "spot/v3/private/cross-margin-loan", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostSpotV3PrivateCrossMarginRepay":                     {Path: "spot/v3/private/cross-margin-repay", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostAssetV3PrivateTransferInterTransfer":               {Path: "asset/v3/private/transfer/inter-transfer", Host: HostPrivate, Method: "POST", Cost: 150},
				"privatePostAssetV3PrivateWithdrawCreate":                      {Path: "asset/v3/private/withdraw/create", Host: HostPrivate, Method: "POST", Cost: 300},
				"privatePostAssetV3PrivateWithdrawCancel":                      {Path: "asset/v3/private/withdraw/cancel", Host: HostPrivate, Method: "POST", Cost: 50},
				"privatePostAssetV3PrivateTransferSubMemberTransfer":           {Path: "asset/v3/private/transfer/sub-member-transfer", Host: HostPrivate, Method: "POST", Cost: 150},
				"privatePostAssetV3PrivateTransferTransferSubMemberSave":       {Path: "asset/v3/private/transfer/transfer-sub-member-save", Host: HostPrivate, Method: "POST", Cost: 150},
				"privatePostAssetV3PrivateTransferUniversalTransfer":           {Path: "asset/v3/private/transfer/universal-transfer", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostUserV3PrivateCreateSubMember":                      {Path: "user/v3/private/create-sub-member", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostUserV3PrivateCreateSubApi":                         {Path: "user/v3/private/create-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostUserV3PrivateUpdateApi":                            {Path: "user/v3/private/update-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostUserV3PrivateDeleteApi":                            {Path: "user/v3/private/delete-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostUserV3PrivateUpdateSubApi":                         {Path: "user/v3/private/update-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostUserV3PrivateDeleteSubApi":                         {Path: "user/v3/private/delete-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostContractV3PrivateCopytradingOrderCreate":           {Path: "contract/v3/private/copytrading/order/create", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostContractV3PrivateCopytradingOrderCancel":           {Path: "contract/v3/private/copytrading/order/cancel", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostContractV3PrivateCopytradingOrderClose":            {Path: "contract/v3/private/copytrading/order/close", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostContractV3PrivateCopytradingPositionClose":         {Path: "contract/v3/private/copytrading/position/close", Host: HostPrivate, Method: "POST", Cost: 40},
				"privatePostContractV3PrivateCopytradingPositionSetLeverage":   {Path: "contract/v3/private/copytrading/position/set-leverage", Host: HostPrivate, Method: "POST", Cost: 40},
				"privatePostContractV3PrivateCopytradingWalletTransfer":        {Path: "contract/v3/private/copytrading/wallet/transfer", Host: HostPrivate, Method: "POST", Cost: 25},
				"privatePostContractV3PrivateCopytradingOrderTradingStop":      {Path: "contract/v3/private/copytrading/order/trading-stop", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostContractV3PrivateOrderCreate":                      {Path: "contract/v3/private/order/create", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivateOrderCancel":                      {Path: "contract/v3/private/order/cancel", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivateOrderCancelAll":                   {Path: "contract/v3/private/order/cancel-all", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivateOrderReplace":                     {Path: "contract/v3/private/order/replace", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivatePositionSetAutoAddMargin":         {Path: "contract/v3/private/position/set-auto-add-margin", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivatePositionSwitchIsolated":           {Path: "contract/v3/private/position/switch-isolated", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivatePositionSwitchMode":               {Path: "contract/v3/private/position/switch-mode", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivatePositionSwitchTpslMode":           {Path: "contract/v3/private/position/switch-tpsl-mode", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivatePositionSetLeverage":              {Path: "contract/v3/private/position/set-leverage", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivatePositionTradingStop":              {Path: "contract/v3/private/position/trading-stop", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivatePositionSetRiskLimit":             {Path: "contract/v3/private/position/set-risk-limit", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostContractV3PrivateAccountSetMarginMode":             {Path: "contract/v3/private/account/setMarginMode", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostUnifiedV3PrivateOrderCreate":                       {Path: "unified/v3/private/order/create", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostUnifiedV3PrivateOrderReplace":                      {Path: "unified/v3/private/order/replace", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostUnifiedV3PrivateOrderCancel":                       {Path: "unified/v3/private/order/cancel", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostUnifiedV3PrivateOrderCreateBatch":                  {Path: "unified/v3/private/order/create-batch", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostUnifiedV3PrivateOrderReplaceBatch":                 {Path: "unified/v3/private/order/replace-batch", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostUnifiedV3PrivateOrderCancelBatch":                  {Path: "unified/v3/private/order/cancel-batch", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostUnifiedV3PrivateOrderCancelAll":                    {Path: "unified/v3/private/order/cancel-all", Host: HostPrivate, Method: "POST", Cost: 30},
				"privatePostUnifiedV3PrivatePositionSetLeverage":               {Path: "unified/v3/private/position/set-leverage", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostUnifiedV3PrivatePositionTpslSwitchMode":            {Path: "unified/v3/private/position/tpsl/switch-mode", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostUnifiedV3PrivatePositionSetRiskLimit":              {Path: "unified/v3/private/position/set-risk-limit", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostUnifiedV3PrivatePositionTradingStop":               {Path: "unified/v3/private/position/trading-stop", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostUnifiedV3PrivateAccountUpgradeUnifiedAccount":      {Path: "unified/v3/private/account/upgrade-unified-account", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostUnifiedV3PrivateAccountSetMarginMode":              {Path: "unified/v3/private/account/setMarginMode", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostFhtComplianceTaxV3PrivateRegistertime":             {Path: "fht/compliance/tax/v3/private/registertime", Host: HostPrivate, Method: "POST", Cost: 50},
				"privatePostFhtComplianceTaxV3PrivateCreate":                   {Path: "fht/compliance/tax/v3/private/create", Host: HostPrivate, Method: "POST", Cost: 50},
				"privatePostFhtComplianceTaxV3PrivateStatus":                   {Path: "fht/compliance/tax/v3/private/status", Host: HostPrivate, Method: "POST", Cost: 50},
				"privatePostFhtComplianceTaxV3PrivateUrl":                      {Path: "fht/compliance/tax/v3/private/url", Host: HostPrivate, Method: "POST", Cost: 50},
				"privatePostV5OrderCreate":                                     {Path: "v5/order/create", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostV5OrderAmend":                                      {Path: "v5/order/amend", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5OrderCancel":                                     {Path: "v5/order/cancel", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostV5OrderCancelAll":                                  {Path: "v5/order/cancel-all", Host: HostPrivate, Method: "POST", Cost: 50},
				"privatePostV5OrderCreateBatch":                                {Path: "v5/order/create-batch", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5OrderAmendBatch":                                 {Path: "v5/order/amend-batch", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5OrderCancelBatch":                                {Path: "v5/order/cancel-batch", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5OrderDisconnectedCancelAll":                      {Path: "v5/order/disconnected-cancel-all", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionSetLeverage":                             {Path: "v5/position/set-leverage", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionSwitchIsolated":                          {Path: "v5/position/switch-isolated", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionSetTpslMode":                             {Path: "v5/position/set-tpsl-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionSwitchMode":                              {Path: "v5/position/switch-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionSetRiskLimit":                            {Path: "v5/position/set-risk-limit", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionTradingStop":                             {Path: "v5/position/trading-stop", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionSetAutoAddMargin":                        {Path: "v5/position/set-auto-add-margin", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionAddMargin":                               {Path: "v5/position/add-margin", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionMovePositions":                           {Path: "v5/position/move-positions", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5PositionConfirmPendingMmr":                       {Path: "v5/position/confirm-pending-mmr", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AccountUpgradeToUta":                             {Path: "v5/account/upgrade-to-uta", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AccountQuickRepayment":                           {Path: "v5/account/quick-repayment", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AccountSetMarginMode":                            {Path: "v5/account/set-margin-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AccountSetHedgingMode":                           {Path: "v5/account/set-hedging-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AccountMmpModify":                                {Path: "v5/account/mmp-modify", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AccountMmpReset":                                 {Path: "v5/account/mmp-reset", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AssetExchangeQuoteApply":                         {Path: "v5/asset/exchange/quote-apply", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostV5AssetExchangeConvertExecute":                     {Path: "v5/asset/exchange/convert-execute", Host: HostPrivate, Method: "POST", Cost: 1},
				"privatePostV5AssetTransferInterTransfer":                      {Path: "v5/asset/transfer/inter-transfer", Host: HostPrivate, Method: "POST", Cost: 50},
				"privatePostV5AssetTransferSaveTransferSubMember":              {Path: "v5/asset/transfer/save-transfer-sub-member", Host: HostPrivate, Method: "POST", Cost: 150},
				"privatePostV5AssetTransferUniversalTransfer":                  {Path: "v5/asset/transfer/universal-transfer", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostV5AssetDepositDepositToAccount":                    {Path: "v5/asset/deposit/deposit-to-account", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AssetWithdrawCreate":                             {Path: "v5/asset/withdraw/create", Host: HostPrivate, Method: "POST", Cost: 50},
				"privatePostV5AssetWithdrawCancel":                             {Path: "v5/asset/withdraw/cancel", Host: HostPrivate, Method: "POST", Cost: 50},
				"privatePostV5UserCreateSubMember":                             {Path: "v5/user/create-sub-member", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostV5UserCreateSubApi":                                {Path: "v5/user/create-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostV5UserFrozenSubMember":                             {Path: "v5/user/frozen-sub-member", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostV5UserUpdateApi":                                   {Path: "v5/user/update-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostV5UserUpdateSubApi":                                {Path: "v5/user/update-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostV5UserDeleteApi":                                   {Path: "v5/user/delete-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostV5UserDeleteSubApi":                                {Path: "v5/user/delete-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				"privatePostV5SpotLeverTokenPurchase":                          {Path: "v5/spot-lever-token/purchase", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostV5SpotLeverTokenRedeem":                            {Path: "v5/spot-lever-token/redeem", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostV5SpotMarginTradeSwitchMode":                       {Path: "v5/spot-margin-trade/switch-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5SpotMarginTradeSetLeverage":                      {Path: "v5/spot-margin-trade/set-leverage", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5SpotCrossMarginTradeLoan":                        {Path: "v5/spot-cross-margin-trade/loan", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostV5SpotCrossMarginTradeRepay":                       {Path: "v5/spot-cross-margin-trade/repay", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostV5SpotCrossMarginTradeSwitch":                      {Path: "v5/spot-cross-margin-trade/switch", Host: HostPrivate, Method: "POST", Cost: 2.5},
				"privatePostV5InsLoanAssociationUid":                           {Path: "v5/ins-loan/association-uid", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5LendingPurchase":                                 {Path: "v5/lending/purchase", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5LendingRedeem":                                   {Path: "v5/lending/redeem", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5LendingRedeemCancel":                             {Path: "v5/lending/redeem-cancel", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AccountSetCollateralSwitch":                      {Path: "v5/account/set-collateral-switch", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AccountSetCollateralSwitchBatch":                 {Path: "v5/account/set-collateral-switch-batch", Host: HostPrivate, Method: "POST", Cost: 5},
				"privatePostV5AccountDemoApplyMoney":                           {Path: "v5/account/demo-apply-money", Host: HostPrivate, Method: "POST", Cost: 5},
			},
			Has: map[string]map[string]int{
				"": {
					banexg.ApiFetchTicker:           banexg.HasOk,
					banexg.ApiFetchTickers:          banexg.HasOk,
					banexg.ApiFetchTickerPrice:      banexg.HasFail,
					banexg.ApiLoadLeverageBrackets:  banexg.HasOk,
					banexg.ApiFetchCurrencies:       banexg.HasOk,
					banexg.ApiGetLeverage:           banexg.HasOk,
					banexg.ApiFetchOHLCV:            banexg.HasOk,
					banexg.ApiFetchOrderBook:        banexg.HasOk,
					banexg.ApiFetchOrder:            banexg.HasOk,
					banexg.ApiFetchOrders:           banexg.HasFail,
					banexg.ApiFetchBalance:          banexg.HasOk,
					banexg.ApiFetchAccountPositions: banexg.HasOk,
					banexg.ApiFetchPositions:        banexg.HasOk,
					banexg.ApiFetchOpenOrders:       banexg.HasOk,
					banexg.ApiCreateOrder:           banexg.HasOk,
					banexg.ApiEditOrder:             banexg.HasOk,
					banexg.ApiCancelOrder:           banexg.HasOk,
					banexg.ApiSetLeverage:           banexg.HasOk,
					banexg.ApiCalcMaintMargin:       banexg.HasOk,
					banexg.ApiWatchOrderBooks:       banexg.HasOk,
					banexg.ApiUnWatchOrderBooks:     banexg.HasOk,
					banexg.ApiWatchOHLCVs:           banexg.HasOk,
					banexg.ApiUnWatchOHLCVs:         banexg.HasOk,
					banexg.ApiWatchMarkPrices:       banexg.HasOk,
					banexg.ApiUnWatchMarkPrices:     banexg.HasOk,
					banexg.ApiWatchTrades:           banexg.HasOk,
					banexg.ApiUnWatchTrades:         banexg.HasOk,
					banexg.ApiWatchMyTrades:         banexg.HasOk,
					banexg.ApiWatchBalance:          banexg.HasOk,
					banexg.ApiWatchPositions:        banexg.HasOk,
					banexg.ApiWatchAccountConfig:    banexg.HasFail,
				},
			},
			CredKeys: map[string]bool{"ApiKey": true, "Secret": true},
		},
	}
	exg.Sign = makeSign(exg)
	exg.FetchCurrencies = makeFetchCurr(exg)
	exg.FetchMarkets = makeFetchMarkets(exg)
	err := exg.Init()
	return exg, err
}

func NewExchange(Options map[string]interface{}) (banexg.BanExchange, *errs.Error) {
	return New(Options)
}
