package bybit

import (
	"github.com/banbox/banexg"
	"github.com/banbox/banexg/errs"
)

func New(Options map[string]interface{}) (*Bybit, *errs.Error) {
	hostName := "bybit.com"
	apiTest := "https://api-testnet." + hostName
	apiProd := "https://api." + hostName
	wsTestBase := "wss://stream-testnet.bybit.com/v5"
	wsProdBase := "wss://stream.bybit.com/v5"
	api := func(path, host, method string, cost float64, cacheSecs ...int) *banexg.Entry {
		e := &banexg.Entry{Path: path, Host: host, Method: method, Cost: cost}
		if len(cacheSecs) > 0 {
			e.CacheSecs = cacheSecs[0]
		}
		return e
	}
	exg := &Bybit{
		Exchange: &banexg.Exchange{
			ExgInfo: &banexg.ExgInfo{
				ID:        "bybit",
				Name:      "Bybit",
				Countries: []string{"VG"},
			},
			RateLimit:  20,
			Options:    Options,
			TimeFrames: timeFrameMap,
			Hosts: &banexg.ExgHosts{
				Test: map[string]string{
					HostPublic:          apiTest,
					HostPrivate:         apiTest,
					HostWsPublicSpot:    wsTestBase + "/public/spot",
					HostWsPublicLinear:  wsTestBase + "/public/linear",
					HostWsPublicInverse: wsTestBase + "/public/inverse",
					HostWsPublicOption:  wsTestBase + "/public/option",
					HostWsPrivate:       wsTestBase + "/private",
				},
				Prod: map[string]string{
					HostPublic:          apiProd,
					HostPrivate:         apiProd,
					HostWsPublicSpot:    wsProdBase + "/public/spot",
					HostWsPublicLinear:  wsProdBase + "/public/linear",
					HostWsPublicInverse: wsProdBase + "/public/inverse",
					HostWsPublicOption:  wsProdBase + "/public/option",
					HostWsPrivate:       wsProdBase + "/private",
				},
				Www: "https://www.bybit.com",
				Doc: []string{
					"https://bybit-exchange.github.io/docs/",
				},
				Fees: "https://www.bybit.com/en/help-center/article/Trading-Fee-Structure",
			},
			Fees: &banexg.ExgFee{
				Main: &banexg.TradeFee{
					FeeSide:    "get",
					TierBased:  false,
					Percentage: true,
					Taker:      0.001,
					Maker:      0.001,
				},
				Linear: &banexg.TradeFee{
					FeeSide:    "quote",
					TierBased:  false,
					Percentage: true,
					Taker:      0.00055,
					Maker:      0.0002,
				},
				Inverse: &banexg.TradeFee{
					FeeSide:    "base",
					TierBased:  false,
					Percentage: true,
					Taker:      0.00055,
					Maker:      0.0002,
				},
				Option: &banexg.TradeFee{
					FeeSide:    "quote",
					TierBased:  false,
					Percentage: true,
					Taker:      0.0002,
					Maker:      0.0002,
				},
			},
			Apis: map[string]*banexg.Entry{
				MethodPublicGetSpotV3PublicSymbols:                                 api("spot/v3/public/symbols", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicQuoteDepth:                              api("spot/v3/public/quote/depth", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicQuoteDepthMerged:                        api("spot/v3/public/quote/depth/merged", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicQuoteTrades:                             api("spot/v3/public/quote/trades", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicQuoteKline:                              api("spot/v3/public/quote/kline", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicQuoteTicker24hr:                         api("spot/v3/public/quote/ticker/24hr", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicQuoteTickerPrice:                        api("spot/v3/public/quote/ticker/price", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicQuoteTickerBookTicker:                   api("spot/v3/public/quote/ticker/bookTicker", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicServerTime:                              api("spot/v3/public/server-time", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicInfos:                                   api("spot/v3/public/infos", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicMarginProductInfos:                      api("spot/v3/public/margin-product-infos", HostPublic, "GET", 1),
				MethodPublicGetSpotV3PublicMarginEnsureTokens:                      api("spot/v3/public/margin-ensure-tokens", HostPublic, "GET", 1),
				MethodPublicGetV3PublicTime:                                        api("v3/public/time", HostPublic, "GET", 1),
				MethodPublicGetContractV3PublicCopytradingSymbolList:               api("contract/v3/public/copytrading/symbol/list", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicOrderBookL2:                      api("derivatives/v3/public/order-book/L2", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicKline:                            api("derivatives/v3/public/kline", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicTickers:                          api("derivatives/v3/public/tickers", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicInstrumentsInfo:                  api("derivatives/v3/public/instruments-info", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicMarkPriceKline:                   api("derivatives/v3/public/mark-price-kline", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicIndexPriceKline:                  api("derivatives/v3/public/index-price-kline", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicFundingHistoryFundingRate:        api("derivatives/v3/public/funding/history-funding-rate", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicRiskLimitList:                    api("derivatives/v3/public/risk-limit/list", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicDeliveryPrice:                    api("derivatives/v3/public/delivery-price", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicRecentTrade:                      api("derivatives/v3/public/recent-trade", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicOpenInterest:                     api("derivatives/v3/public/open-interest", HostPublic, "GET", 1),
				MethodPublicGetDerivativesV3PublicInsurance:                        api("derivatives/v3/public/insurance", HostPublic, "GET", 1),
				MethodPublicGetV5AnnouncementsIndex:                                api("v5/announcements/index", HostPublic, "GET", 5),
				MethodPublicGetV5MarketTime:                                        api("v5/market/time", HostPublic, "GET", 5),
				MethodPublicGetV5MarketKline:                                       api("v5/market/kline", HostPublic, "GET", 5),
				MethodPublicGetV5MarketMarkPriceKline:                              api("v5/market/mark-price-kline", HostPublic, "GET", 5),
				MethodPublicGetV5MarketIndexPriceKline:                             api("v5/market/index-price-kline", HostPublic, "GET", 5),
				MethodPublicGetV5MarketPremiumIndexPriceKline:                      api("v5/market/premium-index-price-kline", HostPublic, "GET", 5),
				MethodPublicGetV5MarketInstrumentsInfo:                             api("v5/market/instruments-info", HostPublic, "GET", 5, 3600),
				MethodPublicGetV5MarketOrderbook:                                   api("v5/market/orderbook", HostPublic, "GET", 5),
				MethodPublicGetV5MarketTickers:                                     api("v5/market/tickers", HostPublic, "GET", 5),
				MethodPublicGetV5MarketFundingHistory:                              api("v5/market/funding/history", HostPublic, "GET", 5),
				MethodPublicGetV5MarketRecentTrade:                                 api("v5/market/recent-trade", HostPublic, "GET", 5),
				MethodPublicGetV5MarketOpenInterest:                                api("v5/market/open-interest", HostPublic, "GET", 5),
				MethodPublicGetV5MarketHistoricalVolatility:                        api("v5/market/historical-volatility", HostPublic, "GET", 5),
				MethodPublicGetV5MarketInsurance:                                   api("v5/market/insurance", HostPublic, "GET", 5),
				MethodPublicGetV5MarketRiskLimit:                                   api("v5/market/risk-limit", HostPublic, "GET", 5),
				MethodPublicGetV5MarketDeliveryPrice:                               api("v5/market/delivery-price", HostPublic, "GET", 5),
				MethodPublicGetV5MarketAccountRatio:                                api("v5/market/account-ratio", HostPublic, "GET", 5),
				MethodPublicGetV5SpotLeverTokenInfo:                                api("v5/spot-lever-token/info", HostPublic, "GET", 5),
				MethodPublicGetV5SpotLeverTokenReference:                           api("v5/spot-lever-token/reference", HostPublic, "GET", 5),
				MethodPublicGetV5SpotMarginTradeData:                               api("v5/spot-margin-trade/data", HostPublic, "GET", 5),
				MethodPublicGetV5SpotCrossMarginTradeData:                          api("v5/spot-cross-margin-trade/data", HostPublic, "GET", 5),
				MethodPublicGetV5SpotCrossMarginTradePledgeToken:                   api("v5/spot-cross-margin-trade/pledge-token", HostPublic, "GET", 5),
				MethodPublicGetV5SpotCrossMarginTradeBorrowToken:                   api("v5/spot-cross-margin-trade/borrow-token", HostPublic, "GET", 5),
				MethodPublicGetV5InsLoanProductInfos:                               api("v5/ins-loan/product-infos", HostPublic, "GET", 5),
				MethodPublicGetV5InsLoanEnsureTokensConvert:                        api("v5/ins-loan/ensure-tokens-convert", HostPublic, "GET", 5),
				MethodPrivateGetV5MarketInstrumentsInfo:                            api("v5/market/instruments-info", HostPrivate, "GET", 5, 3600),
				MethodPrivateGetV2PrivateWalletFundRecords:                         api("v2/private/wallet/fund/records", HostPrivate, "GET", 25),
				MethodPrivateGetSpotV3PrivateOrder:                                 api("spot/v3/private/order", HostPrivate, "GET", 2.5),
				MethodPrivateGetSpotV3PrivateOpenOrders:                            api("spot/v3/private/open-orders", HostPrivate, "GET", 2.5),
				MethodPrivateGetSpotV3PrivateHistoryOrders:                         api("spot/v3/private/history-orders", HostPrivate, "GET", 2.5),
				MethodPrivateGetSpotV3PrivateMyTrades:                              api("spot/v3/private/my-trades", HostPrivate, "GET", 2.5),
				MethodPrivateGetSpotV3PrivateAccount:                               api("spot/v3/private/account", HostPrivate, "GET", 2.5),
				MethodPrivateGetSpotV3PrivateReference:                             api("spot/v3/private/reference", HostPrivate, "GET", 2.5),
				MethodPrivateGetSpotV3PrivateRecord:                                api("spot/v3/private/record", HostPrivate, "GET", 2.5),
				MethodPrivateGetSpotV3PrivateCrossMarginOrders:                     api("spot/v3/private/cross-margin-orders", HostPrivate, "GET", 10),
				MethodPrivateGetSpotV3PrivateCrossMarginAccount:                    api("spot/v3/private/cross-margin-account", HostPrivate, "GET", 10),
				MethodPrivateGetSpotV3PrivateCrossMarginLoanInfo:                   api("spot/v3/private/cross-margin-loan-info", HostPrivate, "GET", 10),
				MethodPrivateGetSpotV3PrivateCrossMarginRepayHistory:               api("spot/v3/private/cross-margin-repay-history", HostPrivate, "GET", 10),
				MethodPrivateGetSpotV3PrivateMarginLoanInfos:                       api("spot/v3/private/margin-loan-infos", HostPrivate, "GET", 10),
				MethodPrivateGetSpotV3PrivateMarginRepaidInfos:                     api("spot/v3/private/margin-repaid-infos", HostPrivate, "GET", 10),
				MethodPrivateGetSpotV3PrivateMarginLtv:                             api("spot/v3/private/margin-ltv", HostPrivate, "GET", 10),
				MethodPrivateGetAssetV3PrivateTransferInterTransferListQuery:       api("asset/v3/private/transfer/inter-transfer/list/query", HostPrivate, "GET", 50),
				MethodPrivateGetAssetV3PrivateTransferSubMemberListQuery:           api("asset/v3/private/transfer/sub-member/list/query", HostPrivate, "GET", 50),
				MethodPrivateGetAssetV3PrivateTransferSubMemberTransferListQuery:   api("asset/v3/private/transfer/sub-member-transfer/list/query", HostPrivate, "GET", 50),
				MethodPrivateGetAssetV3PrivateTransferUniversalTransferListQuery:   api("asset/v3/private/transfer/universal-transfer/list/query", HostPrivate, "GET", 25),
				MethodPrivateGetAssetV3PrivateCoinInfoQuery:                        api("asset/v3/private/coin-info/query", HostPrivate, "GET", 25),
				MethodPrivateGetAssetV3PrivateDepositAddressQuery:                  api("asset/v3/private/deposit/address/query", HostPrivate, "GET", 10),
				MethodPrivateGetContractV3PrivateCopytradingOrderList:              api("contract/v3/private/copytrading/order/list", HostPrivate, "GET", 30),
				MethodPrivateGetContractV3PrivateCopytradingPositionList:           api("contract/v3/private/copytrading/position/list", HostPrivate, "GET", 40),
				MethodPrivateGetContractV3PrivateCopytradingWalletBalance:          api("contract/v3/private/copytrading/wallet/balance", HostPrivate, "GET", 25),
				MethodPrivateGetContractV3PrivatePositionLimitInfo:                 api("contract/v3/private/position/limit-info", HostPrivate, "GET", 25),
				MethodPrivateGetContractV3PrivateOrderUnfilledOrders:               api("contract/v3/private/order/unfilled-orders", HostPrivate, "GET", 1),
				MethodPrivateGetContractV3PrivateOrderList:                         api("contract/v3/private/order/list", HostPrivate, "GET", 1),
				MethodPrivateGetContractV3PrivatePositionList:                      api("contract/v3/private/position/list", HostPrivate, "GET", 1),
				MethodPrivateGetContractV3PrivateExecutionList:                     api("contract/v3/private/execution/list", HostPrivate, "GET", 1),
				MethodPrivateGetContractV3PrivatePositionClosedPnl:                 api("contract/v3/private/position/closed-pnl", HostPrivate, "GET", 1),
				MethodPrivateGetContractV3PrivateAccountWalletBalance:              api("contract/v3/private/account/wallet/balance", HostPrivate, "GET", 1),
				MethodPrivateGetContractV3PrivateAccountFeeRate:                    api("contract/v3/private/account/fee-rate", HostPrivate, "GET", 1),
				MethodPrivateGetContractV3PrivateAccountWalletFundRecords:          api("contract/v3/private/account/wallet/fund-records", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateOrderUnfilledOrders:                api("unified/v3/private/order/unfilled-orders", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateOrderList:                          api("unified/v3/private/order/list", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivatePositionList:                       api("unified/v3/private/position/list", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateExecutionList:                      api("unified/v3/private/execution/list", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateDeliveryRecord:                     api("unified/v3/private/delivery-record", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateSettlementRecord:                   api("unified/v3/private/settlement-record", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateAccountWalletBalance:               api("unified/v3/private/account/wallet/balance", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateAccountTransactionLog:              api("unified/v3/private/account/transaction-log", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateAccountBorrowHistory:               api("unified/v3/private/account/borrow-history", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateAccountBorrowRate:                  api("unified/v3/private/account/borrow-rate", HostPrivate, "GET", 1),
				MethodPrivateGetUnifiedV3PrivateAccountInfo:                        api("unified/v3/private/account/info", HostPrivate, "GET", 1),
				MethodPrivateGetUserV3PrivateFrozenSubMember:                       api("user/v3/private/frozen-sub-member", HostPrivate, "GET", 10),
				MethodPrivateGetUserV3PrivateQuerySubMembers:                       api("user/v3/private/query-sub-members", HostPrivate, "GET", 5),
				MethodPrivateGetUserV3PrivateQueryApi:                              api("user/v3/private/query-api", HostPrivate, "GET", 5),
				MethodPrivateGetUserV3PrivateGetMemberType:                         api("user/v3/private/get-member-type", HostPrivate, "GET", 1),
				MethodPrivateGetAssetV3PrivateTransferTransferCoinListQuery:        api("asset/v3/private/transfer/transfer-coin/list/query", HostPrivate, "GET", 50),
				MethodPrivateGetAssetV3PrivateTransferAccountCoinBalanceQuery:      api("asset/v3/private/transfer/account-coin/balance/query", HostPrivate, "GET", 50),
				MethodPrivateGetAssetV3PrivateTransferAccountCoinsBalanceQuery:     api("asset/v3/private/transfer/account-coins/balance/query", HostPrivate, "GET", 25),
				MethodPrivateGetAssetV3PrivateTransferAssetInfoQuery:               api("asset/v3/private/transfer/asset-info/query", HostPrivate, "GET", 50),
				MethodPrivateGetAssetV3PublicDepositAllowedDepositListQuery:        api("asset/v3/public/deposit/allowed-deposit-list/query", HostPrivate, "GET", 0.17),
				MethodPrivateGetAssetV3PrivateDepositRecordQuery:                   api("asset/v3/private/deposit/record/query", HostPrivate, "GET", 10),
				MethodPrivateGetAssetV3PrivateWithdrawRecordQuery:                  api("asset/v3/private/withdraw/record/query", HostPrivate, "GET", 10),
				MethodPrivateGetV5OrderRealtime:                                    api("v5/order/realtime", HostPrivate, "GET", 5),
				MethodPrivateGetV5OrderHistory:                                     api("v5/order/history", HostPrivate, "GET", 5),
				MethodPrivateGetV5OrderSpotBorrowCheck:                             api("v5/order/spot-borrow-check", HostPrivate, "GET", 1),
				MethodPrivateGetV5PositionList:                                     api("v5/position/list", HostPrivate, "GET", 5),
				MethodPrivateGetV5ExecutionList:                                    api("v5/execution/list", HostPrivate, "GET", 5),
				MethodPrivateGetV5PositionClosedPnl:                                api("v5/position/closed-pnl", HostPrivate, "GET", 5),
				MethodPrivateGetV5PositionMoveHistory:                              api("v5/position/move-history", HostPrivate, "GET", 5),
				MethodPrivateGetV5PreUpgradeOrderHistory:                           api("v5/pre-upgrade/order/history", HostPrivate, "GET", 5),
				MethodPrivateGetV5PreUpgradeExecutionList:                          api("v5/pre-upgrade/execution/list", HostPrivate, "GET", 5),
				MethodPrivateGetV5PreUpgradePositionClosedPnl:                      api("v5/pre-upgrade/position/closed-pnl", HostPrivate, "GET", 5),
				MethodPrivateGetV5PreUpgradeAccountTransactionLog:                  api("v5/pre-upgrade/account/transaction-log", HostPrivate, "GET", 5),
				MethodPrivateGetV5PreUpgradeAssetDeliveryRecord:                    api("v5/pre-upgrade/asset/delivery-record", HostPrivate, "GET", 5),
				MethodPrivateGetV5PreUpgradeAssetSettlementRecord:                  api("v5/pre-upgrade/asset/settlement-record", HostPrivate, "GET", 5),
				MethodPrivateGetV5AccountWalletBalance:                             api("v5/account/wallet-balance", HostPrivate, "GET", 1),
				MethodPrivateGetV5AccountBorrowHistory:                             api("v5/account/borrow-history", HostPrivate, "GET", 1),
				MethodPrivateGetV5AccountCollateralInfo:                            api("v5/account/collateral-info", HostPrivate, "GET", 1),
				MethodPrivateGetV5AssetCoinGreeks:                                  api("v5/asset/coin-greeks", HostPrivate, "GET", 1),
				MethodPrivateGetV5AccountFeeRate:                                   api("v5/account/fee-rate", HostPrivate, "GET", 10),
				MethodPrivateGetV5AccountInfo:                                      api("v5/account/info", HostPrivate, "GET", 5),
				MethodPrivateGetV5AccountTransactionLog:                            api("v5/account/transaction-log", HostPrivate, "GET", 1),
				MethodPrivateGetV5AccountContractTransactionLog:                    api("v5/account/contract-transaction-log", HostPrivate, "GET", 1),
				MethodPrivateGetV5AccountSmpGroup:                                  api("v5/account/smp-group", HostPrivate, "GET", 1),
				MethodPrivateGetV5AccountMmpState:                                  api("v5/account/mmp-state", HostPrivate, "GET", 5),
				MethodPrivateGetV5AssetExchangeQueryCoinList:                       api("v5/asset/exchange/query-coin-list", HostPrivate, "GET", 0.5),
				MethodPrivateGetV5AssetExchangeConvertResultQuery:                  api("v5/asset/exchange/convert-result-query", HostPrivate, "GET", 0.5),
				MethodPrivateGetV5AssetExchangeQueryConvertHistory:                 api("v5/asset/exchange/query-convert-history", HostPrivate, "GET", 0.5),
				MethodPrivateGetV5AssetExchangeOrderRecord:                         api("v5/asset/exchange/order-record", HostPrivate, "GET", 5),
				MethodPrivateGetV5AssetDeliveryRecord:                              api("v5/asset/delivery-record", HostPrivate, "GET", 5),
				MethodPrivateGetV5AssetSettlementRecord:                            api("v5/asset/settlement-record", HostPrivate, "GET", 5),
				MethodPrivateGetV5AssetTransferQueryAssetInfo:                      api("v5/asset/transfer/query-asset-info", HostPrivate, "GET", 50),
				MethodPrivateGetV5AssetTransferQueryAccountCoinsBalance:            api("v5/asset/transfer/query-account-coins-balance", HostPrivate, "GET", 25),
				MethodPrivateGetV5AssetTransferQueryAccountCoinBalance:             api("v5/asset/transfer/query-account-coin-balance", HostPrivate, "GET", 50),
				MethodPrivateGetV5AssetTransferQueryTransferCoinList:               api("v5/asset/transfer/query-transfer-coin-list", HostPrivate, "GET", 50),
				MethodPrivateGetV5AssetTransferQueryInterTransferList:              api("v5/asset/transfer/query-inter-transfer-list", HostPrivate, "GET", 50),
				MethodPrivateGetV5AssetTransferQuerySubMemberList:                  api("v5/asset/transfer/query-sub-member-list", HostPrivate, "GET", 50),
				MethodPrivateGetV5AssetTransferQueryUniversalTransferList:          api("v5/asset/transfer/query-universal-transfer-list", HostPrivate, "GET", 25),
				MethodPrivateGetV5AssetDepositQueryAllowedList:                     api("v5/asset/deposit/query-allowed-list", HostPrivate, "GET", 5),
				MethodPrivateGetV5AssetDepositQueryRecord:                          api("v5/asset/deposit/query-record", HostPrivate, "GET", 10),
				MethodPrivateGetV5AssetDepositQuerySubMemberRecord:                 api("v5/asset/deposit/query-sub-member-record", HostPrivate, "GET", 10),
				MethodPrivateGetV5AssetDepositQueryInternalRecord:                  api("v5/asset/deposit/query-internal-record", HostPrivate, "GET", 5),
				MethodPrivateGetV5AssetDepositQueryAddress:                         api("v5/asset/deposit/query-address", HostPrivate, "GET", 10),
				MethodPrivateGetV5AssetDepositQuerySubMemberAddress:                api("v5/asset/deposit/query-sub-member-address", HostPrivate, "GET", 10),
				MethodPrivateGetV5AssetCoinQueryInfo:                               api("v5/asset/coin/query-info", HostPrivate, "GET", 28, 3600),
				MethodPrivateGetV5AssetWithdrawQueryRecord:                         api("v5/asset/withdraw/query-record", HostPrivate, "GET", 10),
				MethodPrivateGetV5AssetWithdrawWithdrawableAmount:                  api("v5/asset/withdraw/withdrawable-amount", HostPrivate, "GET", 5),
				MethodPrivateGetV5AssetWithdrawVaspList:                            api("v5/asset/withdraw/vasp/list", HostPrivate, "GET", 5),
				MethodPrivateGetV5UserQuerySubMembers:                              api("v5/user/query-sub-members", HostPrivate, "GET", 5),
				MethodPrivateGetV5UserQueryApi:                                     api("v5/user/query-api", HostPrivate, "GET", 5),
				MethodPrivateGetV5UserSubApikeys:                                   api("v5/user/sub-apikeys", HostPrivate, "GET", 5),
				MethodPrivateGetV5UserGetMemberType:                                api("v5/user/get-member-type", HostPrivate, "GET", 5),
				MethodPrivateGetV5UserAffCustomerInfo:                              api("v5/user/aff-customer-info", HostPrivate, "GET", 5),
				MethodPrivateGetV5UserDelSubmember:                                 api("v5/user/del-submember", HostPrivate, "GET", 5),
				MethodPrivateGetV5UserSubmembers:                                   api("v5/user/submembers", HostPrivate, "GET", 5),
				MethodPrivateGetV5SpotLeverTokenOrderRecord:                        api("v5/spot-lever-token/order-record", HostPrivate, "GET", 1),
				MethodPrivateGetV5SpotMarginTradeInterestRateHistory:               api("v5/spot-margin-trade/interest-rate-history", HostPrivate, "GET", 5),
				MethodPrivateGetV5SpotMarginTradeState:                             api("v5/spot-margin-trade/state", HostPrivate, "GET", 5),
				MethodPrivateGetV5SpotCrossMarginTradeLoanInfo:                     api("v5/spot-cross-margin-trade/loan-info", HostPrivate, "GET", 1),
				MethodPrivateGetV5SpotCrossMarginTradeAccount:                      api("v5/spot-cross-margin-trade/account", HostPrivate, "GET", 1),
				MethodPrivateGetV5SpotCrossMarginTradeOrders:                       api("v5/spot-cross-margin-trade/orders", HostPrivate, "GET", 1),
				MethodPrivateGetV5SpotCrossMarginTradeRepayHistory:                 api("v5/spot-cross-margin-trade/repay-history", HostPrivate, "GET", 1),
				MethodPrivateGetV5InsLoanProductInfos:                              api("v5/ins-loan/product-infos", HostPrivate, "GET", 5),
				MethodPrivateGetV5InsLoanEnsureTokensConvert:                       api("v5/ins-loan/ensure-tokens-convert", HostPrivate, "GET", 5),
				MethodPrivateGetV5InsLoanLoanOrder:                                 api("v5/ins-loan/loan-order", HostPrivate, "GET", 5),
				MethodPrivateGetV5InsLoanRepaidHistory:                             api("v5/ins-loan/repaid-history", HostPrivate, "GET", 5),
				MethodPrivateGetV5InsLoanLtvConvert:                                api("v5/ins-loan/ltv-convert", HostPrivate, "GET", 5),
				MethodPrivateGetV5LendingInfo:                                      api("v5/lending/info", HostPrivate, "GET", 5),
				MethodPrivateGetV5LendingHistoryOrder:                              api("v5/lending/history-order", HostPrivate, "GET", 5),
				MethodPrivateGetV5LendingAccount:                                   api("v5/lending/account", HostPrivate, "GET", 5),
				MethodPrivateGetV5BrokerEarningRecord:                              api("v5/broker/earning-record", HostPrivate, "GET", 5),
				MethodPrivateGetV5BrokerEarningsInfo:                               api("v5/broker/earnings-info", HostPrivate, "GET", 5),
				MethodPrivateGetV5BrokerAccountInfo:                                api("v5/broker/account-info", HostPrivate, "GET", 5),
				MethodPrivateGetV5BrokerAssetQuerySubMemberDepositRecord:           api("v5/broker/asset/query-sub-member-deposit-record", HostPrivate, "GET", 10),
				MethodPrivatePostOptionUsdcOpenapiPrivateV1PlaceOrder:              api("option/usdc/openapi/private/v1/place-order", HostPrivate, "POST", 2.5),
				MethodPrivatePostOptionUsdcOpenapiPrivateV1ReplaceOrder:            api("option/usdc/openapi/private/v1/replace-order", HostPrivate, "POST", 2.5),
				MethodPrivatePostOptionUsdcOpenapiPrivateV1CancelOrder:             api("option/usdc/openapi/private/v1/cancel-order", HostPrivate, "POST", 2.5),
				MethodPrivatePostOptionUsdcOpenapiPrivateV1CancelAll:               api("option/usdc/openapi/private/v1/cancel-all", HostPrivate, "POST", 2.5),
				MethodPrivatePostOptionUsdcOpenapiPrivateV1QueryActiveOrders:       api("option/usdc/openapi/private/v1/query-active-orders", HostPrivate, "POST", 2.5),
				MethodPrivatePostOptionUsdcOpenapiPrivateV1QueryOrderHistory:       api("option/usdc/openapi/private/v1/query-order-history", HostPrivate, "POST", 2.5),
				MethodPrivatePostOptionUsdcOpenapiPrivateV1ExecutionList:           api("option/usdc/openapi/private/v1/execution-list", HostPrivate, "POST", 2.5),
				MethodPrivatePostOptionUsdcOpenapiPrivateV1QueryPosition:           api("option/usdc/openapi/private/v1/query-position", HostPrivate, "POST", 2.5),
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1PlaceOrder:           api("perpetual/usdc/openapi/private/v1/place-order", HostPrivate, "POST", 2.5),
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1ReplaceOrder:         api("perpetual/usdc/openapi/private/v1/replace-order", HostPrivate, "POST", 2.5),
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1CancelOrder:          api("perpetual/usdc/openapi/private/v1/cancel-order", HostPrivate, "POST", 2.5),
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1CancelAll:            api("perpetual/usdc/openapi/private/v1/cancel-all", HostPrivate, "POST", 2.5),
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1PositionLeverageSave: api("perpetual/usdc/openapi/private/v1/position/leverage/save", HostPrivate, "POST", 2.5),
				MethodPrivatePostSpotV3PrivateOrder:                                api("spot/v3/private/order", HostPrivate, "POST", 2.5),
				MethodPrivatePostSpotV3PrivateCancelOrder:                          api("spot/v3/private/cancel-order", HostPrivate, "POST", 2.5),
				MethodPrivatePostSpotV3PrivateCancelOrders:                         api("spot/v3/private/cancel-orders", HostPrivate, "POST", 2.5),
				MethodPrivatePostSpotV3PrivateCancelOrdersByIds:                    api("spot/v3/private/cancel-orders-by-ids", HostPrivate, "POST", 2.5),
				MethodPrivatePostSpotV3PrivatePurchase:                             api("spot/v3/private/purchase", HostPrivate, "POST", 2.5),
				MethodPrivatePostSpotV3PrivateRedeem:                               api("spot/v3/private/redeem", HostPrivate, "POST", 2.5),
				MethodPrivatePostSpotV3PrivateCrossMarginLoan:                      api("spot/v3/private/cross-margin-loan", HostPrivate, "POST", 10),
				MethodPrivatePostSpotV3PrivateCrossMarginRepay:                     api("spot/v3/private/cross-margin-repay", HostPrivate, "POST", 10),
				MethodPrivatePostAssetV3PrivateTransferInterTransfer:               api("asset/v3/private/transfer/inter-transfer", HostPrivate, "POST", 150),
				MethodPrivatePostAssetV3PrivateWithdrawCreate:                      api("asset/v3/private/withdraw/create", HostPrivate, "POST", 300),
				MethodPrivatePostAssetV3PrivateWithdrawCancel:                      api("asset/v3/private/withdraw/cancel", HostPrivate, "POST", 50),
				MethodPrivatePostAssetV3PrivateTransferSubMemberTransfer:           api("asset/v3/private/transfer/sub-member-transfer", HostPrivate, "POST", 150),
				MethodPrivatePostAssetV3PrivateTransferTransferSubMemberSave:       api("asset/v3/private/transfer/transfer-sub-member-save", HostPrivate, "POST", 150),
				MethodPrivatePostAssetV3PrivateTransferUniversalTransfer:           api("asset/v3/private/transfer/universal-transfer", HostPrivate, "POST", 10),
				MethodPrivatePostUserV3PrivateCreateSubMember:                      api("user/v3/private/create-sub-member", HostPrivate, "POST", 10),
				MethodPrivatePostUserV3PrivateCreateSubApi:                         api("user/v3/private/create-sub-api", HostPrivate, "POST", 10),
				MethodPrivatePostUserV3PrivateUpdateApi:                            api("user/v3/private/update-api", HostPrivate, "POST", 10),
				MethodPrivatePostUserV3PrivateDeleteApi:                            api("user/v3/private/delete-api", HostPrivate, "POST", 10),
				MethodPrivatePostUserV3PrivateUpdateSubApi:                         api("user/v3/private/update-sub-api", HostPrivate, "POST", 10),
				MethodPrivatePostUserV3PrivateDeleteSubApi:                         api("user/v3/private/delete-sub-api", HostPrivate, "POST", 10),
				MethodPrivatePostContractV3PrivateCopytradingOrderCreate:           api("contract/v3/private/copytrading/order/create", HostPrivate, "POST", 30),
				MethodPrivatePostContractV3PrivateCopytradingOrderCancel:           api("contract/v3/private/copytrading/order/cancel", HostPrivate, "POST", 30),
				MethodPrivatePostContractV3PrivateCopytradingOrderClose:            api("contract/v3/private/copytrading/order/close", HostPrivate, "POST", 30),
				MethodPrivatePostContractV3PrivateCopytradingPositionClose:         api("contract/v3/private/copytrading/position/close", HostPrivate, "POST", 40),
				MethodPrivatePostContractV3PrivateCopytradingPositionSetLeverage:   api("contract/v3/private/copytrading/position/set-leverage", HostPrivate, "POST", 40),
				MethodPrivatePostContractV3PrivateCopytradingWalletTransfer:        api("contract/v3/private/copytrading/wallet/transfer", HostPrivate, "POST", 25),
				MethodPrivatePostContractV3PrivateCopytradingOrderTradingStop:      api("contract/v3/private/copytrading/order/trading-stop", HostPrivate, "POST", 2.5),
				MethodPrivatePostContractV3PrivateOrderCreate:                      api("contract/v3/private/order/create", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivateOrderCancel:                      api("contract/v3/private/order/cancel", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivateOrderCancelAll:                   api("contract/v3/private/order/cancel-all", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivateOrderReplace:                     api("contract/v3/private/order/replace", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivatePositionSetAutoAddMargin:         api("contract/v3/private/position/set-auto-add-margin", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivatePositionSwitchIsolated:           api("contract/v3/private/position/switch-isolated", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivatePositionSwitchMode:               api("contract/v3/private/position/switch-mode", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivatePositionSwitchTpslMode:           api("contract/v3/private/position/switch-tpsl-mode", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivatePositionSetLeverage:              api("contract/v3/private/position/set-leverage", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivatePositionTradingStop:              api("contract/v3/private/position/trading-stop", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivatePositionSetRiskLimit:             api("contract/v3/private/position/set-risk-limit", HostPrivate, "POST", 1),
				MethodPrivatePostContractV3PrivateAccountSetMarginMode:             api("contract/v3/private/account/setMarginMode", HostPrivate, "POST", 1),
				MethodPrivatePostUnifiedV3PrivateOrderCreate:                       api("unified/v3/private/order/create", HostPrivate, "POST", 30),
				MethodPrivatePostUnifiedV3PrivateOrderReplace:                      api("unified/v3/private/order/replace", HostPrivate, "POST", 30),
				MethodPrivatePostUnifiedV3PrivateOrderCancel:                       api("unified/v3/private/order/cancel", HostPrivate, "POST", 30),
				MethodPrivatePostUnifiedV3PrivateOrderCreateBatch:                  api("unified/v3/private/order/create-batch", HostPrivate, "POST", 30),
				MethodPrivatePostUnifiedV3PrivateOrderReplaceBatch:                 api("unified/v3/private/order/replace-batch", HostPrivate, "POST", 30),
				MethodPrivatePostUnifiedV3PrivateOrderCancelBatch:                  api("unified/v3/private/order/cancel-batch", HostPrivate, "POST", 30),
				MethodPrivatePostUnifiedV3PrivateOrderCancelAll:                    api("unified/v3/private/order/cancel-all", HostPrivate, "POST", 30),
				MethodPrivatePostUnifiedV3PrivatePositionSetLeverage:               api("unified/v3/private/position/set-leverage", HostPrivate, "POST", 2.5),
				MethodPrivatePostUnifiedV3PrivatePositionTpslSwitchMode:            api("unified/v3/private/position/tpsl/switch-mode", HostPrivate, "POST", 2.5),
				MethodPrivatePostUnifiedV3PrivatePositionSetRiskLimit:              api("unified/v3/private/position/set-risk-limit", HostPrivate, "POST", 2.5),
				MethodPrivatePostUnifiedV3PrivatePositionTradingStop:               api("unified/v3/private/position/trading-stop", HostPrivate, "POST", 2.5),
				MethodPrivatePostUnifiedV3PrivateAccountUpgradeUnifiedAccount:      api("unified/v3/private/account/upgrade-unified-account", HostPrivate, "POST", 2.5),
				MethodPrivatePostUnifiedV3PrivateAccountSetMarginMode:              api("unified/v3/private/account/setMarginMode", HostPrivate, "POST", 2.5),
				MethodPrivatePostFhtComplianceTaxV3PrivateRegistertime:             api("fht/compliance/tax/v3/private/registertime", HostPrivate, "POST", 50),
				MethodPrivatePostFhtComplianceTaxV3PrivateCreate:                   api("fht/compliance/tax/v3/private/create", HostPrivate, "POST", 50),
				MethodPrivatePostFhtComplianceTaxV3PrivateStatus:                   api("fht/compliance/tax/v3/private/status", HostPrivate, "POST", 50),
				MethodPrivatePostFhtComplianceTaxV3PrivateUrl:                      api("fht/compliance/tax/v3/private/url", HostPrivate, "POST", 50),
				MethodPrivatePostV5OrderCreate:                                     api("v5/order/create", HostPrivate, "POST", 2.5),
				MethodPrivatePostV5OrderAmend:                                      api("v5/order/amend", HostPrivate, "POST", 5),
				MethodPrivatePostV5OrderCancel:                                     api("v5/order/cancel", HostPrivate, "POST", 2.5),
				MethodPrivatePostV5OrderCancelAll:                                  api("v5/order/cancel-all", HostPrivate, "POST", 50),
				MethodPrivatePostV5OrderCreateBatch:                                api("v5/order/create-batch", HostPrivate, "POST", 5),
				MethodPrivatePostV5OrderAmendBatch:                                 api("v5/order/amend-batch", HostPrivate, "POST", 5),
				MethodPrivatePostV5OrderCancelBatch:                                api("v5/order/cancel-batch", HostPrivate, "POST", 5),
				MethodPrivatePostV5OrderDisconnectedCancelAll:                      api("v5/order/disconnected-cancel-all", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionSetLeverage:                             api("v5/position/set-leverage", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionSwitchIsolated:                          api("v5/position/switch-isolated", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionSetTpslMode:                             api("v5/position/set-tpsl-mode", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionSwitchMode:                              api("v5/position/switch-mode", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionSetRiskLimit:                            api("v5/position/set-risk-limit", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionTradingStop:                             api("v5/position/trading-stop", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionSetAutoAddMargin:                        api("v5/position/set-auto-add-margin", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionAddMargin:                               api("v5/position/add-margin", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionMovePositions:                           api("v5/position/move-positions", HostPrivate, "POST", 5),
				MethodPrivatePostV5PositionConfirmPendingMmr:                       api("v5/position/confirm-pending-mmr", HostPrivate, "POST", 5),
				MethodPrivatePostV5AccountUpgradeToUta:                             api("v5/account/upgrade-to-uta", HostPrivate, "POST", 5),
				MethodPrivatePostV5AccountQuickRepayment:                           api("v5/account/quick-repayment", HostPrivate, "POST", 5),
				MethodPrivatePostV5AccountSetMarginMode:                            api("v5/account/set-margin-mode", HostPrivate, "POST", 5),
				MethodPrivatePostV5AccountSetHedgingMode:                           api("v5/account/set-hedging-mode", HostPrivate, "POST", 5),
				MethodPrivatePostV5AccountMmpModify:                                api("v5/account/mmp-modify", HostPrivate, "POST", 5),
				MethodPrivatePostV5AccountMmpReset:                                 api("v5/account/mmp-reset", HostPrivate, "POST", 5),
				MethodPrivatePostV5AssetExchangeQuoteApply:                         api("v5/asset/exchange/quote-apply", HostPrivate, "POST", 1),
				MethodPrivatePostV5AssetExchangeConvertExecute:                     api("v5/asset/exchange/convert-execute", HostPrivate, "POST", 1),
				MethodPrivatePostV5AssetTransferInterTransfer:                      api("v5/asset/transfer/inter-transfer", HostPrivate, "POST", 50),
				MethodPrivatePostV5AssetTransferSaveTransferSubMember:              api("v5/asset/transfer/save-transfer-sub-member", HostPrivate, "POST", 150),
				MethodPrivatePostV5AssetTransferUniversalTransfer:                  api("v5/asset/transfer/universal-transfer", HostPrivate, "POST", 10),
				MethodPrivatePostV5AssetDepositDepositToAccount:                    api("v5/asset/deposit/deposit-to-account", HostPrivate, "POST", 5),
				MethodPrivatePostV5AssetWithdrawCreate:                             api("v5/asset/withdraw/create", HostPrivate, "POST", 50),
				MethodPrivatePostV5AssetWithdrawCancel:                             api("v5/asset/withdraw/cancel", HostPrivate, "POST", 50),
				MethodPrivatePostV5UserCreateSubMember:                             api("v5/user/create-sub-member", HostPrivate, "POST", 10),
				MethodPrivatePostV5UserCreateSubApi:                                api("v5/user/create-sub-api", HostPrivate, "POST", 10),
				MethodPrivatePostV5UserFrozenSubMember:                             api("v5/user/frozen-sub-member", HostPrivate, "POST", 10),
				MethodPrivatePostV5UserUpdateApi:                                   api("v5/user/update-api", HostPrivate, "POST", 10),
				MethodPrivatePostV5UserUpdateSubApi:                                api("v5/user/update-sub-api", HostPrivate, "POST", 10),
				MethodPrivatePostV5UserDeleteApi:                                   api("v5/user/delete-api", HostPrivate, "POST", 10),
				MethodPrivatePostV5UserDeleteSubApi:                                api("v5/user/delete-sub-api", HostPrivate, "POST", 10),
				MethodPrivatePostV5SpotLeverTokenPurchase:                          api("v5/spot-lever-token/purchase", HostPrivate, "POST", 2.5),
				MethodPrivatePostV5SpotLeverTokenRedeem:                            api("v5/spot-lever-token/redeem", HostPrivate, "POST", 2.5),
				MethodPrivatePostV5SpotMarginTradeSwitchMode:                       api("v5/spot-margin-trade/switch-mode", HostPrivate, "POST", 5),
				MethodPrivatePostV5SpotMarginTradeSetLeverage:                      api("v5/spot-margin-trade/set-leverage", HostPrivate, "POST", 5),
				MethodPrivatePostV5SpotCrossMarginTradeLoan:                        api("v5/spot-cross-margin-trade/loan", HostPrivate, "POST", 2.5),
				MethodPrivatePostV5SpotCrossMarginTradeRepay:                       api("v5/spot-cross-margin-trade/repay", HostPrivate, "POST", 2.5),
				MethodPrivatePostV5SpotCrossMarginTradeSwitch:                      api("v5/spot-cross-margin-trade/switch", HostPrivate, "POST", 2.5),
				MethodPrivatePostV5InsLoanAssociationUid:                           api("v5/ins-loan/association-uid", HostPrivate, "POST", 5),
				MethodPrivatePostV5LendingPurchase:                                 api("v5/lending/purchase", HostPrivate, "POST", 5),
				MethodPrivatePostV5LendingRedeem:                                   api("v5/lending/redeem", HostPrivate, "POST", 5),
				MethodPrivatePostV5LendingRedeemCancel:                             api("v5/lending/redeem-cancel", HostPrivate, "POST", 5),
				MethodPrivatePostV5AccountSetCollateralSwitch:                      api("v5/account/set-collateral-switch", HostPrivate, "POST", 5),
				MethodPrivatePostV5AccountSetCollateralSwitchBatch:                 api("v5/account/set-collateral-switch-batch", HostPrivate, "POST", 5),
				MethodPrivatePostV5AccountDemoApplyMoney:                           api("v5/account/demo-apply-money", HostPrivate, "POST", 5),
			},
			Has: map[string]map[string]int{
				"": {
					banexg.ApiFetchTicker:           banexg.HasOk,
					banexg.ApiFetchTickers:          banexg.HasOk,
					banexg.ApiFetchTickerPrice:      banexg.HasOk,
					banexg.ApiLoadLeverageBrackets:  banexg.HasOk,
					banexg.ApiFetchCurrencies:       banexg.HasOk,
					banexg.ApiGetLeverage:           banexg.HasOk,
					banexg.ApiFetchOHLCV:            banexg.HasOk,
					banexg.ApiFetchOrderBook:        banexg.HasOk,
					banexg.ApiFetchOrder:            banexg.HasOk,
					banexg.ApiFetchOrders:           banexg.HasOk,
					banexg.ApiFetchBalance:          banexg.HasOk,
					banexg.ApiFetchAccountPositions: banexg.HasOk,
					banexg.ApiFetchPositions:        banexg.HasOk,
					banexg.ApiFetchOpenOrders:       banexg.HasOk,
					banexg.ApiCreateOrder:           banexg.HasOk,
					banexg.ApiEditOrder:             banexg.HasOk,
					banexg.ApiCancelOrder:           banexg.HasOk,
					banexg.ApiSetLeverage:           banexg.HasOk,
					banexg.ApiCalcMaintMargin:       banexg.HasOk,
					banexg.ApiWatchOrderBooks:       banexg.HasOk,
					banexg.ApiUnWatchOrderBooks:     banexg.HasOk,
					banexg.ApiWatchOHLCVs:           banexg.HasOk,
					banexg.ApiUnWatchOHLCVs:         banexg.HasOk,
					banexg.ApiWatchMarkPrices:       banexg.HasOk,
					banexg.ApiUnWatchMarkPrices:     banexg.HasOk,
					banexg.ApiWatchTrades:           banexg.HasOk,
					banexg.ApiUnWatchTrades:         banexg.HasOk,
					banexg.ApiWatchMyTrades:         banexg.HasOk,
					banexg.ApiWatchBalance:          banexg.HasOk,
					banexg.ApiWatchPositions:        banexg.HasOk,
					banexg.ApiWatchAccountConfig:    banexg.HasOk,
				},
			},
			CredKeys: map[string]bool{"ApiKey": true, "Secret": true},
		},
	}
	exg.Sign = makeSign(exg)
	exg.FetchCurrencies = makeFetchCurr(exg)
	exg.FetchMarkets = makeFetchMarkets(exg)
	exg.CheckWsTimeout = makeCheckWsTimeout(exg)
	err := exg.Init()
	return exg, err
}
