package bybit

import (
	"github.com/banbox/banexg"
	"github.com/banbox/banexg/errs"
)

func New(Options map[string]interface{}) (*Bybit, *errs.Error) {
	hostName := "bybit.com"
	exg := &Bybit{
		Exchange: &banexg.Exchange{
			ExgInfo: &banexg.ExgInfo{
				ID:        "bybit",
				Name:      "Bybit",
				Countries: []string{"VG"},
			},
			RateLimit: 20,
			Options:   Options,
			Hosts: &banexg.ExgHosts{
				Test: map[string]string{
					HostPublic:  "https://api-testnet." + hostName,
					HostPrivate: "https://api-testnet." + hostName,
				},
				Prod: map[string]string{
					HostPublic:  "https://api." + hostName,
					HostPrivate: "https://api." + hostName,
				},
				Www: "https://www.bybit.com",
				Doc: []string{
					"https://bybit-exchange.github.io/docs/",
				},
				Fees: "https://www.bybit.com/en/help-center/article/Trading-Fee-Structure",
			},
			Fees: &banexg.ExgFee{
				Main: &banexg.TradeFee{
					FeeSide:    "get",
					TierBased:  false,
					Percentage: true,
					Taker:      0.001,
					Maker:      0.001,
				},
				Linear: &banexg.TradeFee{
					FeeSide:    "quote",
					TierBased:  false,
					Percentage: true,
					Taker:      0.00055,
					Maker:      0.0002,
				},
				Inverse: &banexg.TradeFee{
					FeeSide:    "base",
					TierBased:  false,
					Percentage: true,
					Taker:      0.00055,
					Maker:      0.0002,
				},
				Option: &banexg.TradeFee{
					FeeSide:    "quote",
					TierBased:  false,
					Percentage: true,
					Taker:      0.0002,
					Maker:      0.0002,
				},
			},
			Apis: map[string]*banexg.Entry{
				MethodPublicGetSpotV3PublicSymbols:                                 {Path: "spot/v3/public/symbols", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicQuoteDepth:                              {Path: "spot/v3/public/quote/depth", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicQuoteDepthMerged:                        {Path: "spot/v3/public/quote/depth/merged", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicQuoteTrades:                             {Path: "spot/v3/public/quote/trades", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicQuoteKline:                              {Path: "spot/v3/public/quote/kline", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicQuoteTicker24hr:                         {Path: "spot/v3/public/quote/ticker/24hr", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicQuoteTickerPrice:                        {Path: "spot/v3/public/quote/ticker/price", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicQuoteTickerBookTicker:                   {Path: "spot/v3/public/quote/ticker/bookTicker", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicServerTime:                              {Path: "spot/v3/public/server-time", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicInfos:                                   {Path: "spot/v3/public/infos", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicMarginProductInfos:                      {Path: "spot/v3/public/margin-product-infos", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetSpotV3PublicMarginEnsureTokens:                      {Path: "spot/v3/public/margin-ensure-tokens", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetV3PublicTime:                                        {Path: "v3/public/time", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetContractV3PublicCopytradingSymbolList:               {Path: "contract/v3/public/copytrading/symbol/list", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicOrderBookL2:                      {Path: "derivatives/v3/public/order-book/L2", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicKline:                            {Path: "derivatives/v3/public/kline", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicTickers:                          {Path: "derivatives/v3/public/tickers", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicInstrumentsInfo:                  {Path: "derivatives/v3/public/instruments-info", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicMarkPriceKline:                   {Path: "derivatives/v3/public/mark-price-kline", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicIndexPriceKline:                  {Path: "derivatives/v3/public/index-price-kline", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicFundingHistoryFundingRate:        {Path: "derivatives/v3/public/funding/history-funding-rate", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicRiskLimitList:                    {Path: "derivatives/v3/public/risk-limit/list", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicDeliveryPrice:                    {Path: "derivatives/v3/public/delivery-price", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicRecentTrade:                      {Path: "derivatives/v3/public/recent-trade", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicOpenInterest:                     {Path: "derivatives/v3/public/open-interest", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetDerivativesV3PublicInsurance:                        {Path: "derivatives/v3/public/insurance", Host: HostPublic, Method: "GET", Cost: 1},
				MethodPublicGetV5AnnouncementsIndex:                                {Path: "v5/announcements/index", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketTime:                                        {Path: "v5/market/time", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketKline:                                       {Path: "v5/market/kline", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketMarkPriceKline:                              {Path: "v5/market/mark-price-kline", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketIndexPriceKline:                             {Path: "v5/market/index-price-kline", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketPremiumIndexPriceKline:                      {Path: "v5/market/premium-index-price-kline", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketInstrumentsInfo:                             {Path: "v5/market/instruments-info", Host: HostPublic, Method: "GET", CacheSecs: 3600, Cost: 5},
				MethodPublicGetV5MarketOrderbook:                                   {Path: "v5/market/orderbook", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketTickers:                                     {Path: "v5/market/tickers", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketFundingHistory:                              {Path: "v5/market/funding/history", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketRecentTrade:                                 {Path: "v5/market/recent-trade", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketOpenInterest:                                {Path: "v5/market/open-interest", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketHistoricalVolatility:                        {Path: "v5/market/historical-volatility", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketInsurance:                                   {Path: "v5/market/insurance", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketRiskLimit:                                   {Path: "v5/market/risk-limit", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketDeliveryPrice:                               {Path: "v5/market/delivery-price", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5MarketAccountRatio:                                {Path: "v5/market/account-ratio", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5SpotLeverTokenInfo:                                {Path: "v5/spot-lever-token/info", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5SpotLeverTokenReference:                           {Path: "v5/spot-lever-token/reference", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5SpotMarginTradeData:                               {Path: "v5/spot-margin-trade/data", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5SpotCrossMarginTradeData:                          {Path: "v5/spot-cross-margin-trade/data", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5SpotCrossMarginTradePledgeToken:                   {Path: "v5/spot-cross-margin-trade/pledge-token", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5SpotCrossMarginTradeBorrowToken:                   {Path: "v5/spot-cross-margin-trade/borrow-token", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5InsLoanProductInfos:                               {Path: "v5/ins-loan/product-infos", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPublicGetV5InsLoanEnsureTokensConvert:                        {Path: "v5/ins-loan/ensure-tokens-convert", Host: HostPublic, Method: "GET", Cost: 5},
				MethodPrivateGetV5MarketInstrumentsInfo:                            {Path: "v5/market/instruments-info", Host: HostPrivate, Method: "GET", CacheSecs: 3600, Cost: 5},
				MethodPrivateGetV2PrivateWalletFundRecords:                         {Path: "v2/private/wallet/fund/records", Host: HostPrivate, Method: "GET", Cost: 25},
				MethodPrivateGetSpotV3PrivateOrder:                                 {Path: "spot/v3/private/order", Host: HostPrivate, Method: "GET", Cost: 2.5},
				MethodPrivateGetSpotV3PrivateOpenOrders:                            {Path: "spot/v3/private/open-orders", Host: HostPrivate, Method: "GET", Cost: 2.5},
				MethodPrivateGetSpotV3PrivateHistoryOrders:                         {Path: "spot/v3/private/history-orders", Host: HostPrivate, Method: "GET", Cost: 2.5},
				MethodPrivateGetSpotV3PrivateMyTrades:                              {Path: "spot/v3/private/my-trades", Host: HostPrivate, Method: "GET", Cost: 2.5},
				MethodPrivateGetSpotV3PrivateAccount:                               {Path: "spot/v3/private/account", Host: HostPrivate, Method: "GET", Cost: 2.5},
				MethodPrivateGetSpotV3PrivateReference:                             {Path: "spot/v3/private/reference", Host: HostPrivate, Method: "GET", Cost: 2.5},
				MethodPrivateGetSpotV3PrivateRecord:                                {Path: "spot/v3/private/record", Host: HostPrivate, Method: "GET", Cost: 2.5},
				MethodPrivateGetSpotV3PrivateCrossMarginOrders:                     {Path: "spot/v3/private/cross-margin-orders", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetSpotV3PrivateCrossMarginAccount:                    {Path: "spot/v3/private/cross-margin-account", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetSpotV3PrivateCrossMarginLoanInfo:                   {Path: "spot/v3/private/cross-margin-loan-info", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetSpotV3PrivateCrossMarginRepayHistory:               {Path: "spot/v3/private/cross-margin-repay-history", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetSpotV3PrivateMarginLoanInfos:                       {Path: "spot/v3/private/margin-loan-infos", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetSpotV3PrivateMarginRepaidInfos:                     {Path: "spot/v3/private/margin-repaid-infos", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetSpotV3PrivateMarginLtv:                             {Path: "spot/v3/private/margin-ltv", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetAssetV3PrivateTransferInterTransferListQuery:       {Path: "asset/v3/private/transfer/inter-transfer/list/query", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetAssetV3PrivateTransferSubMemberListQuery:           {Path: "asset/v3/private/transfer/sub-member/list/query", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetAssetV3PrivateTransferSubMemberTransferListQuery:   {Path: "asset/v3/private/transfer/sub-member-transfer/list/query", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetAssetV3PrivateTransferUniversalTransferListQuery:   {Path: "asset/v3/private/transfer/universal-transfer/list/query", Host: HostPrivate, Method: "GET", Cost: 25},
				MethodPrivateGetAssetV3PrivateCoinInfoQuery:                        {Path: "asset/v3/private/coin-info/query", Host: HostPrivate, Method: "GET", Cost: 25},
				MethodPrivateGetAssetV3PrivateDepositAddressQuery:                  {Path: "asset/v3/private/deposit/address/query", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetContractV3PrivateCopytradingOrderList:              {Path: "contract/v3/private/copytrading/order/list", Host: HostPrivate, Method: "GET", Cost: 30},
				MethodPrivateGetContractV3PrivateCopytradingPositionList:           {Path: "contract/v3/private/copytrading/position/list", Host: HostPrivate, Method: "GET", Cost: 40},
				MethodPrivateGetContractV3PrivateCopytradingWalletBalance:          {Path: "contract/v3/private/copytrading/wallet/balance", Host: HostPrivate, Method: "GET", Cost: 25},
				MethodPrivateGetContractV3PrivatePositionLimitInfo:                 {Path: "contract/v3/private/position/limit-info", Host: HostPrivate, Method: "GET", Cost: 25},
				MethodPrivateGetContractV3PrivateOrderUnfilledOrders:               {Path: "contract/v3/private/order/unfilled-orders", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetContractV3PrivateOrderList:                         {Path: "contract/v3/private/order/list", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetContractV3PrivatePositionList:                      {Path: "contract/v3/private/position/list", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetContractV3PrivateExecutionList:                     {Path: "contract/v3/private/execution/list", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetContractV3PrivatePositionClosedPnl:                 {Path: "contract/v3/private/position/closed-pnl", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetContractV3PrivateAccountWalletBalance:              {Path: "contract/v3/private/account/wallet/balance", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetContractV3PrivateAccountFeeRate:                    {Path: "contract/v3/private/account/fee-rate", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetContractV3PrivateAccountWalletFundRecords:          {Path: "contract/v3/private/account/wallet/fund-records", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateOrderUnfilledOrders:                {Path: "unified/v3/private/order/unfilled-orders", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateOrderList:                          {Path: "unified/v3/private/order/list", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivatePositionList:                       {Path: "unified/v3/private/position/list", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateExecutionList:                      {Path: "unified/v3/private/execution/list", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateDeliveryRecord:                     {Path: "unified/v3/private/delivery-record", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateSettlementRecord:                   {Path: "unified/v3/private/settlement-record", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateAccountWalletBalance:               {Path: "unified/v3/private/account/wallet/balance", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateAccountTransactionLog:              {Path: "unified/v3/private/account/transaction-log", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateAccountBorrowHistory:               {Path: "unified/v3/private/account/borrow-history", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateAccountBorrowRate:                  {Path: "unified/v3/private/account/borrow-rate", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUnifiedV3PrivateAccountInfo:                        {Path: "unified/v3/private/account/info", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetUserV3PrivateFrozenSubMember:                       {Path: "user/v3/private/frozen-sub-member", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetUserV3PrivateQuerySubMembers:                       {Path: "user/v3/private/query-sub-members", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetUserV3PrivateQueryApi:                              {Path: "user/v3/private/query-api", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetUserV3PrivateGetMemberType:                         {Path: "user/v3/private/get-member-type", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetAssetV3PrivateTransferTransferCoinListQuery:        {Path: "asset/v3/private/transfer/transfer-coin/list/query", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetAssetV3PrivateTransferAccountCoinBalanceQuery:      {Path: "asset/v3/private/transfer/account-coin/balance/query", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetAssetV3PrivateTransferAccountCoinsBalanceQuery:     {Path: "asset/v3/private/transfer/account-coins/balance/query", Host: HostPrivate, Method: "GET", Cost: 25},
				MethodPrivateGetAssetV3PrivateTransferAssetInfoQuery:               {Path: "asset/v3/private/transfer/asset-info/query", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetAssetV3PublicDepositAllowedDepositListQuery:        {Path: "asset/v3/public/deposit/allowed-deposit-list/query", Host: HostPrivate, Method: "GET", Cost: 0.17},
				MethodPrivateGetAssetV3PrivateDepositRecordQuery:                   {Path: "asset/v3/private/deposit/record/query", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetAssetV3PrivateWithdrawRecordQuery:                  {Path: "asset/v3/private/withdraw/record/query", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetV5OrderRealtime:                                    {Path: "v5/order/realtime", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5OrderHistory:                                     {Path: "v5/order/history", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5OrderSpotBorrowCheck:                             {Path: "v5/order/spot-borrow-check", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5PositionList:                                     {Path: "v5/position/list", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5ExecutionList:                                    {Path: "v5/execution/list", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5PositionClosedPnl:                                {Path: "v5/position/closed-pnl", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5PositionMoveHistory:                              {Path: "v5/position/move-history", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5PreUpgradeOrderHistory:                           {Path: "v5/pre-upgrade/order/history", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5PreUpgradeExecutionList:                          {Path: "v5/pre-upgrade/execution/list", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5PreUpgradePositionClosedPnl:                      {Path: "v5/pre-upgrade/position/closed-pnl", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5PreUpgradeAccountTransactionLog:                  {Path: "v5/pre-upgrade/account/transaction-log", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5PreUpgradeAssetDeliveryRecord:                    {Path: "v5/pre-upgrade/asset/delivery-record", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5PreUpgradeAssetSettlementRecord:                  {Path: "v5/pre-upgrade/asset/settlement-record", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5AccountWalletBalance:                             {Path: "v5/account/wallet-balance", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5AccountBorrowHistory:                             {Path: "v5/account/borrow-history", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5AccountCollateralInfo:                            {Path: "v5/account/collateral-info", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5AssetCoinGreeks:                                  {Path: "v5/asset/coin-greeks", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5AccountFeeRate:                                   {Path: "v5/account/fee-rate", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetV5AccountInfo:                                      {Path: "v5/account/info", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5AccountTransactionLog:                            {Path: "v5/account/transaction-log", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5AccountContractTransactionLog:                    {Path: "v5/account/contract-transaction-log", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5AccountSmpGroup:                                  {Path: "v5/account/smp-group", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5AccountMmpState:                                  {Path: "v5/account/mmp-state", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5AssetExchangeQueryCoinList:                       {Path: "v5/asset/exchange/query-coin-list", Host: HostPrivate, Method: "GET", Cost: 0.5},
				MethodPrivateGetV5AssetExchangeConvertResultQuery:                  {Path: "v5/asset/exchange/convert-result-query", Host: HostPrivate, Method: "GET", Cost: 0.5},
				MethodPrivateGetV5AssetExchangeQueryConvertHistory:                 {Path: "v5/asset/exchange/query-convert-history", Host: HostPrivate, Method: "GET", Cost: 0.5},
				MethodPrivateGetV5AssetExchangeOrderRecord:                         {Path: "v5/asset/exchange/order-record", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5AssetDeliveryRecord:                              {Path: "v5/asset/delivery-record", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5AssetSettlementRecord:                            {Path: "v5/asset/settlement-record", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5AssetTransferQueryAssetInfo:                      {Path: "v5/asset/transfer/query-asset-info", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetV5AssetTransferQueryAccountCoinsBalance:            {Path: "v5/asset/transfer/query-account-coins-balance", Host: HostPrivate, Method: "GET", Cost: 25},
				MethodPrivateGetV5AssetTransferQueryAccountCoinBalance:             {Path: "v5/asset/transfer/query-account-coin-balance", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetV5AssetTransferQueryTransferCoinList:               {Path: "v5/asset/transfer/query-transfer-coin-list", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetV5AssetTransferQueryInterTransferList:              {Path: "v5/asset/transfer/query-inter-transfer-list", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetV5AssetTransferQuerySubMemberList:                  {Path: "v5/asset/transfer/query-sub-member-list", Host: HostPrivate, Method: "GET", Cost: 50},
				MethodPrivateGetV5AssetTransferQueryUniversalTransferList:          {Path: "v5/asset/transfer/query-universal-transfer-list", Host: HostPrivate, Method: "GET", Cost: 25},
				MethodPrivateGetV5AssetDepositQueryAllowedList:                     {Path: "v5/asset/deposit/query-allowed-list", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5AssetDepositQueryRecord:                          {Path: "v5/asset/deposit/query-record", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetV5AssetDepositQuerySubMemberRecord:                 {Path: "v5/asset/deposit/query-sub-member-record", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetV5AssetDepositQueryInternalRecord:                  {Path: "v5/asset/deposit/query-internal-record", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5AssetDepositQueryAddress:                         {Path: "v5/asset/deposit/query-address", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetV5AssetDepositQuerySubMemberAddress:                {Path: "v5/asset/deposit/query-sub-member-address", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetV5AssetCoinQueryInfo:                               {Path: "v5/asset/coin/query-info", Host: HostPrivate, Method: "GET", CacheSecs: 3600, Cost: 28},
				MethodPrivateGetV5AssetWithdrawQueryRecord:                         {Path: "v5/asset/withdraw/query-record", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivateGetV5AssetWithdrawWithdrawableAmount:                  {Path: "v5/asset/withdraw/withdrawable-amount", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5AssetWithdrawVaspList:                            {Path: "v5/asset/withdraw/vasp/list", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5UserQuerySubMembers:                              {Path: "v5/user/query-sub-members", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5UserQueryApi:                                     {Path: "v5/user/query-api", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5UserSubApikeys:                                   {Path: "v5/user/sub-apikeys", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5UserGetMemberType:                                {Path: "v5/user/get-member-type", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5UserAffCustomerInfo:                              {Path: "v5/user/aff-customer-info", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5UserDelSubmember:                                 {Path: "v5/user/del-submember", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5UserSubmembers:                                   {Path: "v5/user/submembers", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5SpotLeverTokenOrderRecord:                        {Path: "v5/spot-lever-token/order-record", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5SpotMarginTradeInterestRateHistory:               {Path: "v5/spot-margin-trade/interest-rate-history", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5SpotMarginTradeState:                             {Path: "v5/spot-margin-trade/state", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5SpotCrossMarginTradeLoanInfo:                     {Path: "v5/spot-cross-margin-trade/loan-info", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5SpotCrossMarginTradeAccount:                      {Path: "v5/spot-cross-margin-trade/account", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5SpotCrossMarginTradeOrders:                       {Path: "v5/spot-cross-margin-trade/orders", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5SpotCrossMarginTradeRepayHistory:                 {Path: "v5/spot-cross-margin-trade/repay-history", Host: HostPrivate, Method: "GET", Cost: 1},
				MethodPrivateGetV5InsLoanProductInfos:                              {Path: "v5/ins-loan/product-infos", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5InsLoanEnsureTokensConvert:                       {Path: "v5/ins-loan/ensure-tokens-convert", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5InsLoanLoanOrder:                                 {Path: "v5/ins-loan/loan-order", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5InsLoanRepaidHistory:                             {Path: "v5/ins-loan/repaid-history", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5InsLoanLtvConvert:                                {Path: "v5/ins-loan/ltv-convert", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5LendingInfo:                                      {Path: "v5/lending/info", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5LendingHistoryOrder:                              {Path: "v5/lending/history-order", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5LendingAccount:                                   {Path: "v5/lending/account", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5BrokerEarningRecord:                              {Path: "v5/broker/earning-record", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5BrokerEarningsInfo:                               {Path: "v5/broker/earnings-info", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5BrokerAccountInfo:                                {Path: "v5/broker/account-info", Host: HostPrivate, Method: "GET", Cost: 5},
				MethodPrivateGetV5BrokerAssetQuerySubMemberDepositRecord:           {Path: "v5/broker/asset/query-sub-member-deposit-record", Host: HostPrivate, Method: "GET", Cost: 10},
				MethodPrivatePostOptionUsdcOpenapiPrivateV1PlaceOrder:              {Path: "option/usdc/openapi/private/v1/place-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostOptionUsdcOpenapiPrivateV1ReplaceOrder:            {Path: "option/usdc/openapi/private/v1/replace-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostOptionUsdcOpenapiPrivateV1CancelOrder:             {Path: "option/usdc/openapi/private/v1/cancel-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostOptionUsdcOpenapiPrivateV1CancelAll:               {Path: "option/usdc/openapi/private/v1/cancel-all", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostOptionUsdcOpenapiPrivateV1QueryActiveOrders:       {Path: "option/usdc/openapi/private/v1/query-active-orders", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostOptionUsdcOpenapiPrivateV1QueryOrderHistory:       {Path: "option/usdc/openapi/private/v1/query-order-history", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostOptionUsdcOpenapiPrivateV1ExecutionList:           {Path: "option/usdc/openapi/private/v1/execution-list", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostOptionUsdcOpenapiPrivateV1QueryPosition:           {Path: "option/usdc/openapi/private/v1/query-position", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1PlaceOrder:           {Path: "perpetual/usdc/openapi/private/v1/place-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1ReplaceOrder:         {Path: "perpetual/usdc/openapi/private/v1/replace-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1CancelOrder:          {Path: "perpetual/usdc/openapi/private/v1/cancel-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1CancelAll:            {Path: "perpetual/usdc/openapi/private/v1/cancel-all", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostPerpetualUsdcOpenapiPrivateV1PositionLeverageSave: {Path: "perpetual/usdc/openapi/private/v1/position/leverage/save", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostSpotV3PrivateOrder:                                {Path: "spot/v3/private/order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostSpotV3PrivateCancelOrder:                          {Path: "spot/v3/private/cancel-order", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostSpotV3PrivateCancelOrders:                         {Path: "spot/v3/private/cancel-orders", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostSpotV3PrivateCancelOrdersByIds:                    {Path: "spot/v3/private/cancel-orders-by-ids", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostSpotV3PrivatePurchase:                             {Path: "spot/v3/private/purchase", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostSpotV3PrivateRedeem:                               {Path: "spot/v3/private/redeem", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostSpotV3PrivateCrossMarginLoan:                      {Path: "spot/v3/private/cross-margin-loan", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostSpotV3PrivateCrossMarginRepay:                     {Path: "spot/v3/private/cross-margin-repay", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostAssetV3PrivateTransferInterTransfer:               {Path: "asset/v3/private/transfer/inter-transfer", Host: HostPrivate, Method: "POST", Cost: 150},
				MethodPrivatePostAssetV3PrivateWithdrawCreate:                      {Path: "asset/v3/private/withdraw/create", Host: HostPrivate, Method: "POST", Cost: 300},
				MethodPrivatePostAssetV3PrivateWithdrawCancel:                      {Path: "asset/v3/private/withdraw/cancel", Host: HostPrivate, Method: "POST", Cost: 50},
				MethodPrivatePostAssetV3PrivateTransferSubMemberTransfer:           {Path: "asset/v3/private/transfer/sub-member-transfer", Host: HostPrivate, Method: "POST", Cost: 150},
				MethodPrivatePostAssetV3PrivateTransferTransferSubMemberSave:       {Path: "asset/v3/private/transfer/transfer-sub-member-save", Host: HostPrivate, Method: "POST", Cost: 150},
				MethodPrivatePostAssetV3PrivateTransferUniversalTransfer:           {Path: "asset/v3/private/transfer/universal-transfer", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostUserV3PrivateCreateSubMember:                      {Path: "user/v3/private/create-sub-member", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostUserV3PrivateCreateSubApi:                         {Path: "user/v3/private/create-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostUserV3PrivateUpdateApi:                            {Path: "user/v3/private/update-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostUserV3PrivateDeleteApi:                            {Path: "user/v3/private/delete-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostUserV3PrivateUpdateSubApi:                         {Path: "user/v3/private/update-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostUserV3PrivateDeleteSubApi:                         {Path: "user/v3/private/delete-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostContractV3PrivateCopytradingOrderCreate:           {Path: "contract/v3/private/copytrading/order/create", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostContractV3PrivateCopytradingOrderCancel:           {Path: "contract/v3/private/copytrading/order/cancel", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostContractV3PrivateCopytradingOrderClose:            {Path: "contract/v3/private/copytrading/order/close", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostContractV3PrivateCopytradingPositionClose:         {Path: "contract/v3/private/copytrading/position/close", Host: HostPrivate, Method: "POST", Cost: 40},
				MethodPrivatePostContractV3PrivateCopytradingPositionSetLeverage:   {Path: "contract/v3/private/copytrading/position/set-leverage", Host: HostPrivate, Method: "POST", Cost: 40},
				MethodPrivatePostContractV3PrivateCopytradingWalletTransfer:        {Path: "contract/v3/private/copytrading/wallet/transfer", Host: HostPrivate, Method: "POST", Cost: 25},
				MethodPrivatePostContractV3PrivateCopytradingOrderTradingStop:      {Path: "contract/v3/private/copytrading/order/trading-stop", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostContractV3PrivateOrderCreate:                      {Path: "contract/v3/private/order/create", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivateOrderCancel:                      {Path: "contract/v3/private/order/cancel", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivateOrderCancelAll:                   {Path: "contract/v3/private/order/cancel-all", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivateOrderReplace:                     {Path: "contract/v3/private/order/replace", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivatePositionSetAutoAddMargin:         {Path: "contract/v3/private/position/set-auto-add-margin", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivatePositionSwitchIsolated:           {Path: "contract/v3/private/position/switch-isolated", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivatePositionSwitchMode:               {Path: "contract/v3/private/position/switch-mode", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivatePositionSwitchTpslMode:           {Path: "contract/v3/private/position/switch-tpsl-mode", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivatePositionSetLeverage:              {Path: "contract/v3/private/position/set-leverage", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivatePositionTradingStop:              {Path: "contract/v3/private/position/trading-stop", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivatePositionSetRiskLimit:             {Path: "contract/v3/private/position/set-risk-limit", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostContractV3PrivateAccountSetMarginMode:             {Path: "contract/v3/private/account/setMarginMode", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostUnifiedV3PrivateOrderCreate:                       {Path: "unified/v3/private/order/create", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostUnifiedV3PrivateOrderReplace:                      {Path: "unified/v3/private/order/replace", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostUnifiedV3PrivateOrderCancel:                       {Path: "unified/v3/private/order/cancel", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostUnifiedV3PrivateOrderCreateBatch:                  {Path: "unified/v3/private/order/create-batch", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostUnifiedV3PrivateOrderReplaceBatch:                 {Path: "unified/v3/private/order/replace-batch", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostUnifiedV3PrivateOrderCancelBatch:                  {Path: "unified/v3/private/order/cancel-batch", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostUnifiedV3PrivateOrderCancelAll:                    {Path: "unified/v3/private/order/cancel-all", Host: HostPrivate, Method: "POST", Cost: 30},
				MethodPrivatePostUnifiedV3PrivatePositionSetLeverage:               {Path: "unified/v3/private/position/set-leverage", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostUnifiedV3PrivatePositionTpslSwitchMode:            {Path: "unified/v3/private/position/tpsl/switch-mode", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostUnifiedV3PrivatePositionSetRiskLimit:              {Path: "unified/v3/private/position/set-risk-limit", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostUnifiedV3PrivatePositionTradingStop:               {Path: "unified/v3/private/position/trading-stop", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostUnifiedV3PrivateAccountUpgradeUnifiedAccount:      {Path: "unified/v3/private/account/upgrade-unified-account", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostUnifiedV3PrivateAccountSetMarginMode:              {Path: "unified/v3/private/account/setMarginMode", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostFhtComplianceTaxV3PrivateRegistertime:             {Path: "fht/compliance/tax/v3/private/registertime", Host: HostPrivate, Method: "POST", Cost: 50},
				MethodPrivatePostFhtComplianceTaxV3PrivateCreate:                   {Path: "fht/compliance/tax/v3/private/create", Host: HostPrivate, Method: "POST", Cost: 50},
				MethodPrivatePostFhtComplianceTaxV3PrivateStatus:                   {Path: "fht/compliance/tax/v3/private/status", Host: HostPrivate, Method: "POST", Cost: 50},
				MethodPrivatePostFhtComplianceTaxV3PrivateUrl:                      {Path: "fht/compliance/tax/v3/private/url", Host: HostPrivate, Method: "POST", Cost: 50},
				MethodPrivatePostV5OrderCreate:                                     {Path: "v5/order/create", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostV5OrderAmend:                                      {Path: "v5/order/amend", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5OrderCancel:                                     {Path: "v5/order/cancel", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostV5OrderCancelAll:                                  {Path: "v5/order/cancel-all", Host: HostPrivate, Method: "POST", Cost: 50},
				MethodPrivatePostV5OrderCreateBatch:                                {Path: "v5/order/create-batch", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5OrderAmendBatch:                                 {Path: "v5/order/amend-batch", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5OrderCancelBatch:                                {Path: "v5/order/cancel-batch", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5OrderDisconnectedCancelAll:                      {Path: "v5/order/disconnected-cancel-all", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionSetLeverage:                             {Path: "v5/position/set-leverage", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionSwitchIsolated:                          {Path: "v5/position/switch-isolated", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionSetTpslMode:                             {Path: "v5/position/set-tpsl-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionSwitchMode:                              {Path: "v5/position/switch-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionSetRiskLimit:                            {Path: "v5/position/set-risk-limit", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionTradingStop:                             {Path: "v5/position/trading-stop", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionSetAutoAddMargin:                        {Path: "v5/position/set-auto-add-margin", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionAddMargin:                               {Path: "v5/position/add-margin", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionMovePositions:                           {Path: "v5/position/move-positions", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5PositionConfirmPendingMmr:                       {Path: "v5/position/confirm-pending-mmr", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AccountUpgradeToUta:                             {Path: "v5/account/upgrade-to-uta", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AccountQuickRepayment:                           {Path: "v5/account/quick-repayment", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AccountSetMarginMode:                            {Path: "v5/account/set-margin-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AccountSetHedgingMode:                           {Path: "v5/account/set-hedging-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AccountMmpModify:                                {Path: "v5/account/mmp-modify", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AccountMmpReset:                                 {Path: "v5/account/mmp-reset", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AssetExchangeQuoteApply:                         {Path: "v5/asset/exchange/quote-apply", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostV5AssetExchangeConvertExecute:                     {Path: "v5/asset/exchange/convert-execute", Host: HostPrivate, Method: "POST", Cost: 1},
				MethodPrivatePostV5AssetTransferInterTransfer:                      {Path: "v5/asset/transfer/inter-transfer", Host: HostPrivate, Method: "POST", Cost: 50},
				MethodPrivatePostV5AssetTransferSaveTransferSubMember:              {Path: "v5/asset/transfer/save-transfer-sub-member", Host: HostPrivate, Method: "POST", Cost: 150},
				MethodPrivatePostV5AssetTransferUniversalTransfer:                  {Path: "v5/asset/transfer/universal-transfer", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostV5AssetDepositDepositToAccount:                    {Path: "v5/asset/deposit/deposit-to-account", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AssetWithdrawCreate:                             {Path: "v5/asset/withdraw/create", Host: HostPrivate, Method: "POST", Cost: 50},
				MethodPrivatePostV5AssetWithdrawCancel:                             {Path: "v5/asset/withdraw/cancel", Host: HostPrivate, Method: "POST", Cost: 50},
				MethodPrivatePostV5UserCreateSubMember:                             {Path: "v5/user/create-sub-member", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostV5UserCreateSubApi:                                {Path: "v5/user/create-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostV5UserFrozenSubMember:                             {Path: "v5/user/frozen-sub-member", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostV5UserUpdateApi:                                   {Path: "v5/user/update-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostV5UserUpdateSubApi:                                {Path: "v5/user/update-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostV5UserDeleteApi:                                   {Path: "v5/user/delete-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostV5UserDeleteSubApi:                                {Path: "v5/user/delete-sub-api", Host: HostPrivate, Method: "POST", Cost: 10},
				MethodPrivatePostV5SpotLeverTokenPurchase:                          {Path: "v5/spot-lever-token/purchase", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostV5SpotLeverTokenRedeem:                            {Path: "v5/spot-lever-token/redeem", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostV5SpotMarginTradeSwitchMode:                       {Path: "v5/spot-margin-trade/switch-mode", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5SpotMarginTradeSetLeverage:                      {Path: "v5/spot-margin-trade/set-leverage", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5SpotCrossMarginTradeLoan:                        {Path: "v5/spot-cross-margin-trade/loan", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostV5SpotCrossMarginTradeRepay:                       {Path: "v5/spot-cross-margin-trade/repay", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostV5SpotCrossMarginTradeSwitch:                      {Path: "v5/spot-cross-margin-trade/switch", Host: HostPrivate, Method: "POST", Cost: 2.5},
				MethodPrivatePostV5InsLoanAssociationUid:                           {Path: "v5/ins-loan/association-uid", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5LendingPurchase:                                 {Path: "v5/lending/purchase", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5LendingRedeem:                                   {Path: "v5/lending/redeem", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5LendingRedeemCancel:                             {Path: "v5/lending/redeem-cancel", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AccountSetCollateralSwitch:                      {Path: "v5/account/set-collateral-switch", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AccountSetCollateralSwitchBatch:                 {Path: "v5/account/set-collateral-switch-batch", Host: HostPrivate, Method: "POST", Cost: 5},
				MethodPrivatePostV5AccountDemoApplyMoney:                           {Path: "v5/account/demo-apply-money", Host: HostPrivate, Method: "POST", Cost: 5},
			},
			Has: map[string]map[string]int{
				"": {
					banexg.ApiFetchTicker:           banexg.HasOk,
					banexg.ApiFetchTickers:          banexg.HasOk,
					banexg.ApiFetchTickerPrice:      banexg.HasFail,
					banexg.ApiLoadLeverageBrackets:  banexg.HasOk,
					banexg.ApiFetchCurrencies:       banexg.HasOk,
					banexg.ApiGetLeverage:           banexg.HasOk,
					banexg.ApiFetchOHLCV:            banexg.HasOk,
					banexg.ApiFetchOrderBook:        banexg.HasOk,
					banexg.ApiFetchOrder:            banexg.HasOk,
					banexg.ApiFetchOrders:           banexg.HasFail,
					banexg.ApiFetchBalance:          banexg.HasOk,
					banexg.ApiFetchAccountPositions: banexg.HasOk,
					banexg.ApiFetchPositions:        banexg.HasOk,
					banexg.ApiFetchOpenOrders:       banexg.HasOk,
					banexg.ApiCreateOrder:           banexg.HasOk,
					banexg.ApiEditOrder:             banexg.HasOk,
					banexg.ApiCancelOrder:           banexg.HasOk,
					banexg.ApiSetLeverage:           banexg.HasOk,
					banexg.ApiCalcMaintMargin:       banexg.HasOk,
					banexg.ApiWatchOrderBooks:       banexg.HasOk,
					banexg.ApiUnWatchOrderBooks:     banexg.HasOk,
					banexg.ApiWatchOHLCVs:           banexg.HasOk,
					banexg.ApiUnWatchOHLCVs:         banexg.HasOk,
					banexg.ApiWatchMarkPrices:       banexg.HasOk,
					banexg.ApiUnWatchMarkPrices:     banexg.HasOk,
					banexg.ApiWatchTrades:           banexg.HasOk,
					banexg.ApiUnWatchTrades:         banexg.HasOk,
					banexg.ApiWatchMyTrades:         banexg.HasOk,
					banexg.ApiWatchBalance:          banexg.HasOk,
					banexg.ApiWatchPositions:        banexg.HasOk,
					banexg.ApiWatchAccountConfig:    banexg.HasFail,
				},
			},
			CredKeys: map[string]bool{"ApiKey": true, "Secret": true},
		},
	}
	exg.Sign = makeSign(exg)
	exg.FetchCurrencies = makeFetchCurr(exg)
	exg.FetchMarkets = makeFetchMarkets(exg)
	err := exg.Init()
	return exg, err
}

func NewExchange(Options map[string]interface{}) (banexg.BanExchange, *errs.Error) {
	return New(Options)
}
